import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class UbicacionService {

  private departamentos: string[] = [
    'AMAZONAS',
    'ÁNCASH',
    'APURÍMAC',
    'AREQUIPA',
    'AYACUCHO',
    'CAJAMARCA',
    'CALLAO',
    'CUSCO',
    'HUANCAVELICA',
    'HUÁNUCO',
    'ICA',
    'JUNÍN',
    'LA LIBERTAD',
    'LAMBAYEQUE',
    'LIMA',
    'LORETO',
    'MADRE DE DIOS',
    'MOQUEGUA',
    'PASCO',
    'PIURA',
    'PUNO',
    'SAN MARTÍN',
    'TACNA',
    'TUMBES',
    'UCAYALI',
  ];

  private provinciasPorDepartamento: { [key: string]: string[] } = {
    'AMAZONAS': ['CHACHAPOYAS', 'BAGUA', 'UTCUBAMBA', 'LUYA', 'RODRÍGUEZ DE MENDOZA', 'CONDORCANQUI'],
    'ÁNCASH': ['HUARAZ', 'CARHUAZ', 'YUNGAY', 'HUAYLAS', 'AIJA', 'RECUAY'],
    'APURÍMAC': ['ABANCAY', 'ANDAHUAYLAS', 'ANTABAMBA', 'AYMARAES', 'COTABAMBAS', 'GRAU'],
    'AREQUIPA': ['AREQUIPA', 'CAMANÁ', 'CARAVELÍ', 'CASTILLA', 'CAYLLOMA', 'CONDESUYOS'],
    'AYACUCHO': ['HUAMANGA', 'CANGALLO', 'HUANCA SANCOS', 'HUANTA', 'LA MAR', 'LUCANAS', 'PARINACOCHAS', 'PAUCAR DEL SARA SARA', 'SUCRE', 'VICTOR FAJARDO', 'VILCAS HUAMÁN'],
    'CAJAMARCA': ['CAJAMARCA', 'CAJABAMBA', 'CELENDÍN', 'CHOTA', 'CONTUMAZÁ', 'CUTERVO', 'HUALGAYOC', 'JAÉN', 'SAN IGNACIO', 'SAN MARCOS', 'SAN MIGUEL', 'SAN PABLO', 'SANTA CRUZ'],
    'CALLAO': ['CALLAO'],
    'CUSCO': ['CUSCO', 'ACOMAYO', 'ANTA', 'CALCA', 'CANAS', 'CANCHIS', 'CHUMBIVILCAS', 'ESPINAR', 'LA CONVENCIÓN', 'PARURO', 'PAUCARTAMBO', 'QUISPICANCHI', 'URUBAMBA'],
    'HUANCAVELICA': ['HUANCAVELICA', 'ACOBAMBA', 'ANGARAES', 'CASTROVIRREYNA', 'CHURCAMPA', 'HUAYTARA', 'TAYACAJA'],
    'HUÁNUCO': ['HUÁNUCO', 'AMBO', 'DOS DE MAYO', 'HUACAYBAMBA', 'HUAMALÍES', 'LEONCIO PRADO', 'MARAÑÓN', 'PACHITEA', 'PUERTO INCA', 'LAURICOCHA', 'YAROWILCA'],
    'ICA': ['ICA', 'CHINCHA', 'NAZCA', 'PALPA', 'PISCO'],
    'JUNÍN': ['HUANCAYO', 'CONCEPCIÓN', 'CHANCHAMAYO', 'JAUJA', 'JUNÍN', 'SATIPO', 'TARMA', 'YAULI', 'CHUPACA'],
    'LA LIBERTAD': ['TRUJILLO', 'ASCOPE', 'BOLÍVAR', 'CHEPÉN', 'JULCÁN', 'OTUZCO', 'PACASMAYO', 'PATAZ', 'SÁNCHEZ CARRIÓN', 'SANTIAGO DE CHUCO', 'GRAN CHIMÚ', 'VÍRÚ'],
    'LAMBAYEQUE': ['CHICLAYO', 'FERREÑAFE', 'LAMBAYEQUE'],
    'LIMA': ['LIMA', 'BARRANCA', 'CAJATAMBO', 'CANTA', 'CAÑETE', 'HUAURA', 'OYÓN', 'YAUYOS'],
    'LORETO': ['MAYNAS', 'ALTO AMAZONAS', 'LORETO', 'MARISCAL RAMÓN CASTILLA', 'REQUENA', 'UCAYALI'],
    'MADRE DE DIOS': ['TAMBOPATA', 'MANU', 'TAHUAMANU'],
    'MOQUEGUA': ['MARISCAL NIETO', 'GENERAL SÁNCHEZ CERRO', 'ILO'],
    'PASCO': ['PASCO', 'DANIEL ALCIDES CARRIÓN', 'OXAPAMPA'],
    'PIURA': ['PIURA', 'AYABACA', 'HUANCABAMBA', 'MORROPÓN', 'PAITA', 'SULLANA', 'TALARA'],
    'PUNO': ['PUNO', 'AZÁNGARO', 'CARABAYA', 'CHUCUITO', 'EL COLLAO', 'HUANCANÉ', 'LAMPA', 'MELGAR', 'MOHO', 'SAN ANTONIO DE PUTINA', 'SAN ROMÁN', 'SANDIA', 'YUNGUYO'],
    'SAN MARTÍN': ['MOYOBAMBA', 'BELLAVISTA', 'EL DORADO', 'HUALLAGA', 'LAMAS', 'MARISCAL CÁCERES', 'PICOTA', 'RIOJA', 'SAN MARTÍN', 'TOCACHE'],
    'TACNA': ['TACNA', 'CANDARAVE', 'JORGE BASADRE', 'TARATA'],
    'TUMBES': ['TUMBES', 'CONTRALMIRANTE VILLAR', 'ZARUMILLA'],
    'UCAYALI': ['CORONEL PORTILLO', 'ATALAYA', 'PADRE ABAD', 'PURÚS'],
  };
  

  private distritosPorProvincia: { [key: string]: string[] } = {
    //provincias del departamento de amazonas
    'CHACHAPOYAS': ['CHACHAPOYAS', 'ASUNCIÓN', 'BALSAS', 'CHETO', 'CHILIQUÍN', 'CHUQUIBAMBA', 'GRANADA', 'HUANCAS', 'LA JALCA', 'LEIMEBAMBA', 'LEVANTO', 'MAGDALENA', 'MARISCAL CASTILLA', 'MOLINOPAMPA', 'MONTEVIDEO', 'OLLEROS', 'QUINJALCA', 'SAN FRANCISCO DE DAGUAS', 'SAN ISIDRO DE MAINO', 'SOLOCO', 'SONCHE'],
    'UTCUBAMBA': ['BAGUA GRANDE', 'CAJARURO', 'CUMBA', 'EL MILAGRO', 'JAMALCA', 'LONYA GRANDE', 'YAMON'],
    'BAGUA': ['BAGUA', 'ARAMANGO', 'COPALLIN', 'EL PARCO', 'IMAZA', 'LA PECA'],
    'LUYA': ['LAMUD', 'CAMPORREDONDO', 'COCABAMBA', 'COLCAMAR', 'CONILA', 'INGUILPATA', 'LONGUITA', 'LONYA CHICO', 'LUYA', 'LUYA VIEJO', 'MARÍA', 'OCALLI', 'OCUMAL', 'PISUQUIA', 'PROVIDENCIA', 'SAN CRISTÓBAL', 'SAN FRANCISCO DEL YESO', 'SAN JERÓNIMO', 'SAN JUAN DE LOPECANCHA', 'SANTA CATALINA', 'SANTO TOMAS', 'TINGO', 'TRITA'],
    'RODRÍGUEZ DE MENDOZA': ['CHIRIMOTO', 'COCHAMAL', 'HUAMBO', 'LIMABAMBA', 'LONGAR', 'MARISCAL BENAVIDES', 'MILPUC', 'OMIA', 'SAN NICOLÁS', 'SANTA ROSA', 'TOTORA', 'VISTA ALEGRE'],
    'CONDORCANQUI': ['NIEVA', 'EL CENEPA', 'RÍO SANTIAGO'],

    //povincias del departamento de ancash
    'HUARAZ': ['HUARAZ', 'COCHABAMBA', 'COLCABAMBA', 'HUANCHAY', 'INDEPENDENCIA', 'JANGAS', 'LA LIBERTAD', 'OLLEROS', 'PAMPAS GRANDE', 'PARIACOTO', 'PIRA', 'TARICA'],
    'CARHUAZ': ['CARHUAZ', 'ACOCHACA', 'ANTA', 'ATAQUERO', 'MARCARÁ', 'PARIAHUANCA', 'SAN MIGUEL DE ACO', 'SHILLA', 'TINCO', 'YUNGAR'],
    'YUNGAY': ['YUNGAY', 'CASCAPARA', 'MANCOS', 'MATACOTO', 'QUILLO', 'RANRAHIRCA', 'SHUPLUY', 'YANAMA'],
    'HUAYLAS': ['CARAZ', 'HUALLANCA', 'HUATA', 'HUAYLAS', 'MATO', 'PAMPAROMÁS', 'PUEBLO LIBRE', 'SANTA CRUZ', 'SANTO TORIBIO', 'YURACMARCA'],
    'AIJA': ['AIJA', 'CORIS', 'HUACLLAN', 'LA MERCED', 'SUCCHA'],
    'RECUAY': ['RECUAY', 'CATA', 'COTAPARACO', 'HUAYLLAPAMPA', 'LLACLLIN', 'MARCA', 'PAMPAS CHICO', 'PARARIN', 'TAPACOCHA', 'TICAPAMPA'],
    
    //provincas del departamento de APURÍMAC
    'ABANCAY': ['ABANCAY', 'CHACOCHE', 'CIRCA', 'CURAHUASI', 'HUANIPACA', 'LAMBRAMA', 'PICHIRHUA', 'SAN PEDRO DE CACHORA', 'TAMBURCO'],
    'ANDAHUAYLAS': ['ANDAHUAYLAS', 'ANDARAPA', 'CHIARA', 'HUANCARAMA', 'HUANCARAY', 'KISHUARA', 'PACOBAMBA', 'PACUCHA', 'PAMPACHIRI', 'POMACOCHA', 'SAN ANTONIO DE CACHI', 'SAN JERÓNIMO', 'SAN MIGUEL DE CHACCRA', 'SANTA MARÍA DE CHICMO'],
    'ANTABAMBA': ['ANTABAMBA', 'EL ORO', 'HUAQUIRCA', 'JUAN ESPINOZA MEDRANO', 'OROPESA', 'PACHACONAS', 'SABAINO'],
    'AYMARAES': ['CHALHUANCA', 'CAPAYA', 'CARAYBAMBA', 'CHAPIMARCA', 'COLCABAMBA', 'COTARUSE', 'HUAYLLO', 'JUSTO APU SAHUARAURA', 'LUCRE', 'POCOBAMBA', 'SAN JUAN DE CHACÑA', 'SAÑAYCA', 'SORAYA', 'TAPAIRIHUA', 'TINTAY'],
    'COTABAMBAS': ['TAMBOBAMBA', 'COTABAMBAS', 'COYLLURQUI', 'HAQUIRA', 'MARA', 'CHALLHUAHUACHO', 'CHUQUIS', 'CURASCO'],
    'GRAU': ['CHUQUIBAMBILLA', 'CURPAHUASI', 'GAMARRA', 'HUAYLLATI', 'MAMARA', 'MIGUEL AUCHO', 'SANTA ROSA', 'TURPAY', 'VILCABAMBA', 'VIRUNDO'],

    //provincas del departamento de AREQUIPA
    'AREQUIPA': ['AREQUIPA', 'ALTO SELVA ALEGRE', 'CAYMA', 'CERRO COLORADO', 'CHARACATO', 'CHIGUATA', 'JACOBO HUNTER', 'LA JOYA', 'MARIANO MELGAR', 'MIRAFLORES', 'MOLLEBAYA', 'PAUCARPATA', 'POCSI', 'POLOBAYA', 'QUEQUEÑA', 'SABANDÍA', 'SACHACA', 'SAN JUAN DE SIGUAS', 'SAN JUAN DE TARUCANI', 'SANTA ISABEL DE SIGUAS', 'SANTA RITA DE SIGUAS', 'SOCABAYA', 'TIABAYA', 'UCHUMAYO', 'VITOR', 'YANAHUARA', 'YARABAMBA', 'YURA'],
    'CAMANÁ': ['CAMANÁ', 'JOSÉ MARÍA QUIMPER', 'MARIANO NICOLÁS VALCÁRCEL', 'MARISCAL CÁCERES', 'NICOLÁS DE PIEROLA', 'OCOÑA', 'QUILCA', 'SAMUEL PASTOR', 'SOCOS', 'VÍTOR'],
    'CARAVELÍ': ['CARAVELÍ', 'ACARÍ', 'ATICO', 'ATIQUIPA', 'BELLA UNIÓN', 'CAHUACHO', 'CHALA', 'CHAPARRA', 'HUANUHUANU', 'JAQUI', 'LOMAS', 'MARISMA', 'MEJÍA', 'NICOLÁS DE PIEROLA', 'OCONA', 'QUICACHA', 'YAUCA'],
    'CASTILLA': ['ARENALES', 'CHALA', 'CHALACO', 'HUANUHUANU', 'JAQUI', 'LA HUAYA', 'LEONCIO PRADO', 'LLALLI', 'MARISMA', 'SAMUEL PASTOR', 'TIPAN', 'YAUCA'],
    'CAYLLOMA': ['CHIVAY', 'ACHOMA', 'CABANACONDE', 'CALLALLI', 'CAYLLOMA', 'COPORAQUE', 'HUAMBO', 'HUANCA', 'ICHUPAMPA', 'LARI', 'LLUTA', 'MACA', 'MADRIGAL', 'MAJES', 'SAN ANTONIO DE CHUCA', 'SIBAYO', 'TAPAY', 'TISCO', 'TUTI', 'YANQUE'],
    'CONDESUYOS': ['CHUQUIBAMBA', 'ANDARAY', 'CAYARANI', 'CHICHAS', 'IRAY', 'RÍO GRANDE', 'SALAMANCA', 'YANAQUIHUA'],
    'ISLAY': ['MOLLENDO', 'COCACHACRA', 'DEÁN VALDIVIA', 'ISLAY', 'MEJÍA', 'PUNTA DE BOMBÓN'],
    'LA UNIÓN': ['COTAHUASI', 'ALCA', 'CHARCANA', 'HUAYNACOTAS', 'PAMPAMARCA', 'PUYCA', 'QUECHUALLA', 'SAYLA', 'TAURIA', 'TOMEPAMPA', 'TORO'],
  
    //provincas del departamento de AYACUCHO
    'HUAMANGA': ['AYACUCHO', 'ACOCRO', 'ACOS VINCHOS', 'CARMEN ALTO', 'CHIARA', 'JESÚS NAZARENO', 'OCROS', 'PACAYCASA', 'QUINUA', 'SAN JOSÉ DE TICLLAS', 'SAN JUAN BAUTISTA', 'SANTIAGO DE PISCHA', 'SOCOS', 'TAMBILLO', 'VINCHOS'],
    'CANGALLO': ['CANGALLO', 'CHUSCHI', 'LOS MOROCHUCOS', 'MARÍA PARADO DE BELLIDO', 'PARAS', 'TOTOS', 'UCHURACCAY', 'ASQUIPATA', 'CANGALLO', 'SAÑAYCA', 'TANCARIA', 'TOMO'],
    'HUANCA SANCOS': ['HUANCA SANCOS', 'CARAPO', 'SACSAMARCA', 'SANTIAGO DE LUCANAMARCA', 'SANTO TOMÁS DE PATA', 'AYACUCHO'],
    'HUANTA': ['HUANTA', 'AYAHUANCO', 'HUAMANGUILLO', 'IGUAIN', 'LLOCHEGUA', 'LURICOCHA', 'SANTO DOMINGO DE LOS OLLEROS', 'UMARI', 'AYACUCHO'],
    'LA MAR': ['SAN MIGUEL', 'ANCO', 'AYNA', 'CHILCAS', 'CHUNGUI', 'LUIS CARRANZA', 'SANTA ROSA', 'TAMBO', 'SAMUGARI', 'ANCHIHUAY'],
    'LUCANAS': ['PUQUIO', 'AUCARA', 'CABANA', 'CARMEN SALCEDO', 'CHAVIÑA', 'CHIPAO', 'HUAC-HUAS', 'LARAMATE', 'LEONCIO PRADO', 'LUCANAS', 'OCAÑA', 'OTOCA', 'SAURAMA', 'SÍCOS', 'SORA', 'HUACAÑA'],
    'PARINACOCHAS': ['CORACORA', 'CHUMPI', 'CORONEL CASTAÑEDA', 'CORONEL PABLO ARTEAGA', 'HUAMANQUIQUIA', 'PACAPAUSA', 'PULLO', 'PUYUSCA', 'SAN FRANCISCO DE RAVACAYCO', 'UPAHUACHO', 'CORONEL CASTAÑEDA'],
    'PAUCAR DEL SARA SARA': ['PAUSA', 'COLTA', 'CORCULLA', 'LAMPA', 'MARCABAMBA', 'OYOLO', 'PARARCA', 'SAN JAVIER DE ALPABAMBA', 'SAN JOSÉ DE USHUA', 'SARA SARA'],
    'SUCRE': ['QUEROBAMBA', 'BELEN', 'CHALCOS', 'CHILCAYOC', 'HUACAÑA', 'MORCOLLA', 'PAICO', 'SAN PEDRO DE LARCAY', 'SAN SALVADOR DE QUIJE', 'SANTIAGO DE PAUCARAY'],
    'VICTOR FAJARDO': ['HUANCAPI', 'ALCAMENCA', 'APONGO', 'ASQUIPATA', 'CANARIA', 'CAYARA', 'COLCA', 'HUAMANQUIQUIA', 'HUANCARAYLLA', 'HUAYA', 'SARHUA', 'VILCANCHOS'],
    'VILCAS HUAMÁN': ['VILCAS HUAMÁN', 'ACCOMARCA', 'CARHUANCA', 'CONCEPCIÓN', 'HUAMBALPA', 'INDEPENDENCIA', 'SAURAMA', 'VISCHONGO'],

    //provincias del departamento de CAJAMARCA 
    'CAJAMARCA': ['CAJAMARCA', 'ASUNCIÓN', 'CHETILLA', 'COSPÁN', 'ENCHILADA', 'JESÚS', 'LLACANORA', 'LOS BAÑOS DEL INCA', 'MAGDALENA', 'MATARA', 'NAMORA', 'SAN JUAN', 'TECUMSEH', 'TOCOTOCO'],
    'CAJABAMBA': ['CAJABAMBA', 'CACHACHI', 'CONDEBAMBA', 'SITACOCHA'],
    'CELENDÍN': ['CELENDÍN', 'ANGUIA', 'CHUMUCH', 'CORTEGANA', 'HUASMIN', 'JORGE CHÁVEZ', 'JOSÉ GÁLVEZ', 'LA LIBERTAD DE PALLÁN', 'MIGUEL IGLESIAS', 'OXAMARCA', 'SOROCHUCO', 'SUCRE', 'UTCO'],
    'CHOTA': ['CHOTA', 'ANGUIA', 'CHADÍN', 'CHALAMARCA', 'CHIGUIRIP', 'CHIMBÁN', 'CHOROPAMPA', 'COCHABAMBA', 'CONCHAN', 'HUAMBOS', 'LAJAS', 'LLAMA', 'MIRACOSTA', 'PACCHA', 'PION', 'QUEROCOTO', 'SAN JUAN DE LICUPIS', 'TACABAMBA', 'TOCMOCHE'],
    'CONTUMAZÁ': ['CONTUMAZÁ', 'CHILETE', 'CUPISNIQUE', 'GUZMANGO', 'SAN BENITO', 'SANTA CRUZ DE TOLED', 'TANTARICA', 'YONAN'],
    'CUTERVO': ['CUTERVO', 'CALLAYUC', 'CHOROS', 'CUJILLO', 'LA RAMADA', 'PUJCA', 'SÁNCHEZ CARRIÓN', 'SANTO TOMÁS', 'SOCOTA', 'TACABAMBA', 'TOCMOCHE'],
    'HUALGAYOC': ['BAMBAMARCA', 'CHUGUR', 'HUALGAYOC', 'LA ESPERANZA'],
    'JAÉN': ['JAÉN', 'BELLAVISTA', 'CHONTALÍ', 'COLASAY', 'HUABAL', 'LAS PIRIAS', 'POMAHUACA', 'PUCARÁ', 'SALLIQUE', 'SAN FELIPE', 'SAN JOSÉ DEL ALTO', 'SANTA ROSA', 'YAMANGO'],
    'SAN IGNACIO': ['SAN IGNACIO', 'CHIRINOS', 'HUARANGO', 'LA COIPA', 'NAMBALLE', 'SAN IGNACIO', 'SAN JOSÉ DE LOURDES', 'TABACONAS', 'CHONTALÍ', 'COLASAY', 'HUABAL', 'LAS PIRIAS', 'POMAHUACA', 'PUCARÁ', 'SALLIQUE', 'SAN FELIPE', 'SAN JOSÉ DEL ALTO', 'SANTA ROSA', 'YAMANGO'],
    'SAN MARCOS': ['PEDRO GÁLVEZ', 'CHANCAY', 'EDUARDO VILLANUEVA', 'GREGORIO PITA', 'ICHOCÁN', 'JOSÉ MANUEL QUIROZ', 'JOSÉ SABOGAL', 'OTUZO', 'PEDRO GÁLVEZ', 'LA CUESTA', 'MIGUEL IGLESIAS', 'TANGAY'],
    'SAN MIGUEL': ['SAN MIGUEL', 'BOLÍVAR', 'CALQUIS', 'CATILLUC', 'EL PRADO', 'LA FLORIDA', 'LLAPA', 'NANCHOC', 'NIEPOS', 'SAN GREGORIO', 'TONGOD'],
    'SAN PABLO': ['SAN PABLO', 'SAN BERNARDINO', 'SAN LUIS', 'TUMBADÉN'],
    'SANTA CRUZ': ['SANTA CRUZ', 'ANDABAMBA', 'CATACHE', 'CHANCAYBAÑOS', 'LA ESPERANZA', 'NINABAMBA', 'PULÁN', 'SAUCEPAMPA', 'SEXI'],

    //provincias del CALLAO
    'CALLAO': ['CALLAO', 'BELLAVISTA', 'CARMEN DE LA LEGUA REYNOSO', 'LA PERLA', 'LA PUNTA', 'VENTANILLA'],

    //provincias del CUSCO
    'CUSCO': ['CUSCO', 'CCORCA', 'POROY', 'SAN JERÓNIMO', 'SAN SEBASTIÁN', 'SANTIAGO', 'SAYLLA', 'WANCHAQ'],
    'ACOMAYO': ['ACOMAYO', 'ACOPIA', 'MOSOC LLACTA', 'POMACANCHI', 'RONDOCAN', 'SANGARARÁ'],
    'ANTA': ['ANTA', 'ANCAHUASI', 'CACHIMAYO', 'CHINCHAYPUJIO', 'HUAROCONDO', 'LIMATAMBO', 'MOLLEPATA', 'PUCYURA', 'ZURITE'],
    'CALCA': ['CALCA', 'COYA', 'LAMAY', 'LARES', 'PISAC', 'SAN SALVADOR', 'TARAY', 'YANATILE'],
    'CANAS': ['CHECCA', 'KUNTURKANKI', 'LANGUI', 'LAYO', 'PAMPAMARCA', 'QUEHUE', 'TÚPAC AMARU', 'YANAOCO'],
    'CANCHIS': ['CHECACUPE', 'COLQUEMARCA', 'COMBAPATA', 'COPORAQUE', 'LIVITACA', 'MARANGANI', 'SAN PABLO', 'SAN PEDRO', 'SANTA ANA', 'SICUANI', 'TINTA'],
    'CHUMBIVILCAS': ['CCAPACMARCA', 'CHAMACA', 'COLQUEMARCA', 'LIVITACA', 'LLUSCO', 'QUIÑOTA', 'SANTO TOMÁS', 'VELILLE'],
    'LA CONVENCIÓN': ['QUILLABAMBA', 'ECHARATE', 'SANTA ANA', 'VILCABAMBA', 'HUAYOPATA', 'MARANURA', 'OCOBAMBA', 'QUELLOUNO', 'KIMBIRI', 'SANTA TERESA', 'MOLLEPATA', 'LA CONVENCIÓN', 'AYNA', 'SANTA ISABEL', 'VILLA VIRGEN', 'VILLA KINTIARINA', 'MEGANTONI'],
    'PARURO': ['PARURO', 'ACCHA', 'CCAPI', 'COLCHA', 'HUANOQUITE', 'OMACHA', 'PACCARITAMBO', 'PILLPINTO', 'YAURISQUE'],
    'PAUCARTAMBO': ['PAUCARTAMBO', 'CAICAY', 'CHALLABAMBA', 'COLQUEPATA', 'HUANCARANI', 'KOSÑIPATA', 'PAUCARTAMBO', 'QUEHUE', 'TRES UNIDOS'],
    'QUISPICANCHI': ['URCOS', 'ANDAHUAYLILLAS', 'CAMANTI', 'CCARHUAYO', 'CCATCA', 'CUSIPATA', 'HUARO', 'LUCRE', 'MARCAPATA', 'OCONGATE', 'OROPESA', 'QUIQUIJANA', 'URCOS'],
    'URUBAMBA': ['URUBAMBA', 'CHINCHERO', 'HUAYLLABAMBA', 'MACHUPICCHU', 'MARAS', 'OLLANTAYTAMBO', 'YUCAY'],
  
    //provincias del HUANCAVELICA
    'HUANCAVELICA': ['HUANCAVELICA', 'ACOBAMBILLA', 'ACORIA', 'CONAYCA', 'CUENCA', 'HUACHOCOLPA', 'HUAYLLAHUARA', 'IZCUCHACA', 'LARIA', 'MANTA', 'MARISCAL CÁCERES', 'MOYA', 'NUEVO OCCORO', 'PALCA', 'PILCHACA', 'VILCA', 'YAULI', 'ASCENSIÓN'],
    'ACOBAMBILLA': ['ACOBAMBILLA', 'CAPILLAS', 'CARMENZA', 'CHAVINILLO', 'CHIPAO', 'COCHARCAS', 'HUACRADAN', 'HUAYLLAPAMPA', 'SAN JUAN', 'STA ANA', 'STA BARBARA', 'STA ROSA'],
    'ANGARAES': ['LANGA', 'ANTACANGA', 'CALLANMARCA', 'CAYANKI', 'CHAVÍN', 'HUACHOCOLPA', 'HUARIBAMBA', 'HUAYLLAHUARA', 'STA ANA', 'STA BARBARA', 'STA ROSA', 'SUZUCO'],
    'CASTROVIRREYNA': ['CASTROVIRREYNA', 'ARMA', 'AURAHUA', 'CAPILLAS', 'CHUPAMARCA', 'COCAS', 'HUACHOS', 'STA ANA', 'STA BARBARA', 'STA ROSA', 'SANTA TERESA'],
    'CHURCAMPA': ['CHURCAMPA', 'ANCO', 'CHINCHO', 'CONAYCA', 'HUACHOCOLPA', 'HUARIBAMBA', 'HUAYLLAHUARA', 'STA ANA', 'STA BARBARA', 'STA ROSA', 'STA TERESA', 'STA YNEZ', 'STA YSABEL', 'TAMBO'],
    'HUAYTARA': ['HUAYTARA', 'AYAVI', 'CAJATAMBO', 'CHALHUANCA', 'COLCABAMBA', 'DANIEL HERNANDEZ', 'HUAYLLAHUARA', 'STA ANA', 'STA BARBARA', 'STA ROSA', 'STA TERESA', 'STA YSABEL', 'TAMBO', 'VIÑOS'],
    'TAYACAJA': ['PAMPAS', 'ACOSTAMBO', 'ACRAQUIA', 'AHUAYCHA', 'COLCABAMBA', 'DANIEL HERNANDEZ', 'HUACHOCOLPA', 'HUARIBAMBA', 'HUAYLLAHUARA', 'STA ANA', 'STA BARBARA', 'STA ROSA', 'STA TERESA', 'STA YSABEL', 'TAMBO', 'VIÑOS'],
  
    //provincias del departamtento de HUANUCO
    'HUÁNUCO': ['HUÁNUCO', 'AMARILIS', 'CHINCHAO', 'CHURUBAMBA', 'MARGOS', 'QUISQUI', 'SAN FRANCISCO DE CAYRAN', 'SAN PEDRO DE CHAULÁN', 'SANTA MARÍA DEL VALLE'],
    'AMBO': ['AMBO', 'CAYNA', 'COLPAS', 'CONCHAMARCA', 'HUACAR', 'SAN FRANCISCO', 'SAN RAFAEL', 'TOMAY KICHWA'],
    'DOS DE MAYO': ['LA UNIÓN', 'CHUQUIS', 'MARÍAS', 'PACHAS', 'QUIVILLA', 'RIPÁN', 'SHUNQUI', 'SILLAPATA', 'YANAS'],
    'HUACAYBAMBA': ['HUACAYBAMBA', 'CANCHABAMBA', 'COCHABAMBA', 'PINRA'],
    'HUAMALÍES': ['LLATA', 'ARANCAY', 'CHAVÍN DE PARIARCA', 'HUACRACHUCO', 'JACAS GRANDE', 'JIRCAN', 'MIRAFLORES', 'MONZÓN', 'PUNCHAO', 'PUÑOS', 'SINGA', 'TANTAMAYO'],
    'LEONCIO PRADO': ['TARMA', 'ACOBAMBA', 'HUARICOLCA', 'HUASAHUASI', 'LA UNIÓN', 'PALCA', 'PALCAMAYO', 'SAN PEDRO DE CAJAS', 'TAPO'],
    'MARANÓN': ['HUACRACHUCO', 'CHOLON', 'HUAMBOS', 'SAN BUENAVENTURA', 'SAN PABLO DE PILLAO', 'SANTA ANA DE TUSI', 'TUSI'],
    'PUERTO INCA': ['PUERTO INCA', 'CODO DEL POZUZO', 'HONORIA', 'TOURNAVISTA', 'YUYAPICHIS'],
    'YAROWILCA': ['CHAVÍN DE HUÁNTAR', 'CAHUAC', 'CHACABAMBA', 'CHASQUERO', 'CHAVÍN DE HUÁNTAR', 'LAUTARO', 'LLATA', 'MARIAS', 'QUEROCOTILLO', 'QUISQUI', 'SAN MARCOS DE ROCCHAC', 'YANAHUANCA', 'YARUMAYO', 'MIRAFLORES', 'NACARO', 'SAN FRANCISCO DE YAROWILCA'],
  
    //provincias del departamento de ICA
    'ICA': ['ICA', 'LA TINGUIÑA', 'LOS AQUIJES', 'OCUCAJE', 'PACHACÚTEC', 'PARCONA', 'PUEBLO NUEVO', 'SALAS', 'SAN JOSÉ DE LOS MOLINOS', 'SAN JUAN BAUTISTA', 'SANTIAGO', 'SUBTANJALLA', 'YAUCA DEL ROSARIO'],
    'CHINCHA': ['CHINCHA ALTA', 'ALTO LARÁN', 'CHAVÍN', 'CHINCHA ALTA', 'CHINCHA BAJA', 'EL CARMEN', 'GROCIO PRADO', 'PUEBLO NUEVO', 'SAN JUAN DE YANAC', 'SAN PEDRO DE HUACARPANA', 'SUNAMPE', 'TAMBO DE MORA'],
    'NAZCA': ['NAZCA', 'CHANGUILLO', 'EL INGENIO', 'MARCONA', 'NAZCA', 'VISTA ALEGRE'],
    'PALPA': ['PALPA', 'LLIPATA', 'RÍO GRANDE', 'SANTA CRUZ', 'TIBILLO', 'VISTA ALEGRE'],
    'PISCO': ['PISCO', 'HUANCANO', 'HUMAY', 'INDEPENDENCIA', 'PARACAS', 'PISCO', 'SAN ANDRÉS', 'SAN CLEMENTE', 'TÚPAC AMARU INCA'],
  
    //provincias del departamento de JUNIN
    'HUANCAYO': ['HUANCAYO', 'CARHUACALLANGA', 'CHACAPAMPA', 'CHICCHE', 'CHILCA', 'CHONGOS ALTO', 'CHUPURO', 'COLCA', 'CULLHUAS', 'EL TAMBO', 'HUACRAPUQUIO', 'HUALHUAS', 'HUANCAN', 'HUASICANCHA', 'HUAYUCACHI', 'INGENIO', 'PARIAHUANCA', 'PILCOMAYO', 'PUCARÁ', 'QUICHUAY', 'QUILCAS', 'SAN AGUSTÍN', 'SAN JERÓNIMO DE TUNÁN', 'SANTO DOMINGO DE ACOBAMBA', 'SAÑO', 'SAPALLANGA', 'SICAYA', 'VITIS', 'ACO', 'ACOLLA', 'APATA', 'ATAURA', 'CANCHAYLLO', 'CURICACA', 'EL CARMEN', 'HUARIPAMPA', 'ÑAHUIMPUQUIO', 'PACCHA', 'STA CRUZ DE COCACHACRA', 'STA ROSA DE CONDORES', 'TARMA', 'ACOBAMBA', 'HUARICOLCA', 'HUASAHUASI'],
    'CONCEPCIÓN': ['CONCEPCIÓN', 'ACO', 'ANDAMARCA', 'CHAMBARA', 'COCHAS', 'COMAS', 'CONCEPCIÓN', 'HEROÍNAS TOLEDO', 'MANZANARES', 'MATAHUASI', 'MITO', 'NUEVE DE JULIO', 'ORCOTUNA', 'STA ROSA DE OCOPA', 'STA TERESA', 'SANTO DOMINGO DE ACOBAMBA', 'YANACANCHA'],
    'CHANCHAMAYO': ['CHANCHAMAYO', 'PERENE', 'SAN LUIS DE SHUARO', 'VITOC', 'YANAHUANCA'],
    'JAUJA': ['JAUJA', 'ACOLLA', 'APATA', 'ATAURA', 'CANCHAYLLO', 'CURICACA', 'EL CARMEN', 'HUARIPAMPA', 'ÑAHUIMPUQUIO', 'PACCHA', 'STA CRUZ DE COCACHACRA', 'STA ROSA DE CONDORES', 'SICAYA', 'TARMA', 'ACOBAMBA', 'HUARICOLCA', 'HUASAHUASI', 'YAULI', 'CANCHAYLLO', 'CHUPACA', 'HUAMALÍ', 'HUALHUAS', 'HUARIPAMPA', 'HUAYLLAY GRANDE', 'CHUPACA', 'HUAMALÍ', 'HUALHUAS', 'HUARIPAMPA', 'HUAYLLAY GRANDE', 'JULCÁN', 'LEONOR ORDÓÑEZ', 'LLOSA', 'MAZAMARI', 'MUQUI', 'PACA'],
    'JUNÍN': ['JUNÍN', 'CARHUAMAYO', 'ONDORES', 'ULCUMAYO'],
    'SATIPO': ['SATIPO', 'COVIRIALI', 'LLAYLLA', 'MAZAMARI', 'PAMPA HERMOSA', 'PANGOA', 'RÍO NEGRO', 'RÍO TAMBO', 'SANTO DOMINGO DE ACOBAMBA', 'VIZCATÁN DEL ENE', 'JUNÍN'],
    'TARMA': ['TARMA', 'ACOBAMBA', 'HUARICOLCA', 'HUASAHUASI'],
    'YAULI': ['LA OROYA', 'CHACAPALPA', 'HUAY HUAY', 'MARCAPOMACOCHA', 'MOROCOCHA', 'PACCHA', 'STA BÁRBARA DE CARHUACAYAN', 'STA ROSA DE SACCO', 'STA YSABEL DE CONDORSANCA', 'SUITUCANCHA', 'YAULI'],
    'CHUPACA': ['CHUPACA', 'AHUAC', 'CHONGOS BAJO', 'HUACHAC', 'HUAMANCACA CHICO', 'HUARICA', 'HUAYLLATI', 'STA ANA DE HUAYLLAY', 'STA ISABEL DE LLAYLLA', 'STA ROSA DE OCOBAMBA', 'STA YSABEL DE CHUPACA', 'ZAPALLANGA'],
  
    //provincias del departamento LA LIBERTAD
    'TRUJILLO': ['TRUJILLO', 'EL PORVENIR', 'FLORENCIA DE MORA', 'HUANCHACO', 'LA ESPERANZA', 'LAREDO', 'MOCHE', 'POROTO', 'SALAVERRY', 'SIMBAL', 'VICTOR LARCO HERRERA'],
    'ASCOPE': ['ASCOPE', 'CHICAMA', 'CHOCOPE', 'MAGDALENA DE CAO', 'PAIJÁN', 'RAZURI', 'SANTIAGO DE CAO'],
    'BOLÍVAR': ['BOLÍVAR', 'BAMBAMARCA', 'CONDORMARCA', 'LONGOTEA', 'UCHUMARCA', 'UCUNCHA'],
    'CHEPÉN': ['CHEPÉN', 'PACANGA', 'PUEBLO NUEVO'],
    'JULCÁN': ['JULCÁN', 'CARABAMBA', 'HUASO', 'OTUZCO', 'AGALLPAMPA', 'CHARAT', 'HUARANCHAL', 'LA CUESTA', 'MACHE', 'PARANDAY', 'SALPO', 'SINSICAP', 'USQUIL'],
    'OTUZCO': ['OTUZCO', 'AGALLPAMPA', 'CHARAT', 'HUARANCHAL', 'LA CUESTA', 'MACHE', 'PARANDAY', 'SALPO', 'SINSICAP', 'USQUIL'],
    'GRAN CHIMÚ': ['CASCAS', 'LUCMA', 'ANGAS', 'MARMOT', 'SAYAPULLO'],
    'PACASMAYO': ['SAN PEDRO DE LLOC', 'BULDIBUYO', 'CHILLIA', 'HUANCASPATA', 'HUAYLILLAS', 'SAN PEDRO DE LLOC', 'TAYABAMBA', 'UCHUMAYO'],
    'PATAZ': ['TAYABAMBA', 'BULDIBUYO', 'CHILLIA', 'HUANCASPATA', 'HUAYLILLAS', 'UCHUMAYO', 'HUAYO', 'ONA', 'PARCOY', 'PATAZ', 'PIAS', 'SANTIAGO DE CHALLAS'],
    'SÁNCHEZ CARRIÓN': ['HUAMACHUCO', 'COCHORCO', 'CURGOS', 'CHUGAY', 'MARCABAL', 'SANAGORÁN', 'SARÍN', 'SARTIMBAMBA'],
    'SANTIAGO DE CHUCO': ['SANTIAGO DE CHUCO', 'ANGASMARCA', 'CACHICADÁN', 'MOLLEBAMBA', 'MOLLEPATA', 'QUIRUVILCA', 'SANTA CRUZ DE CHUCA', 'SANTIAGO DE CHUCO'],
    'GRANDE': ['SANTIAGO DE CHUCO', 'ANGASMARCA', 'CACHICADÁN', 'MOLLEBAMBA', 'MOLLEPATA', 'QUIRUVILCA', 'SANTA CRUZ DE CHUCA'],
    'VÍCTOR LARCO HERRERA': ['VICTOR LARCO HERRERA', 'EL PORVENIR', 'FLORENCIA DE MORA', 'HUANCHACO', 'LA ESPERANZA', 'LAREDO', 'MOCHE', 'POROTO', 'SALAVERRY', 'SIMBAL', 'TRUJILLO'],
  
    //provincias del departamento de LAMBAYEQUE
    'CHICLAYO': ['CHICLAYO', 'CHONGOYAPE', 'ETÉN', 'ETEN PUERTO', 'LAGUNAS', 'MONSEFÚ', 'NUEVA ARICA', 'OYOTÚN', 'PICSI', 'PIMENTEL', 'REQUE', 'SÁNCHEZ CARRIÓN', 'CHICLAYO'],
    'FERREÑAFE': ['FERREÑAFE', 'CAÑARIS', 'INCAHUASI', 'MANUEL ANTONIO MESONES MURO', 'PITIPO', 'PUEBLO NUEVO', 'TÚCUME'],
    'LAMBAYEQUE': ['LAMBAYEQUE', 'CHOCHOPE', 'ILLIMO', 'JAYANCA', 'LAMBAYEQUE', 'MOTUPE', 'PACORA', 'TÚCUME'],

    //provincias del departamento de LIMA
    'LIMA': ['LIMA', 'ANCON', 'ATE', 'BARRANCO', 'BREÑA', 'CARABAYLLO', 'CHACLACAYO', 'CHORRILLOS', 'CIENEGUILLA', 'COMAS', 'EL AGUSTINO', 'INDEPENDENCIA', 'JESUS MARIA', 'LA MOLINA', 'LA VICTORIA', 'LINCE', 'LOS OLIVOS', 'LURIGANCHO', 'LURIN', 'MAGDALENA DEL MAR', 'MAGDALENA VIEJA', 'MIRAFLORES', 'PACHACAMAC', 'PUCUSANA', 'PUENTE PIEDRA', 'PUNTA HERMOSA', 'PUNTA NEGRA', 'RIMAC', 'SAN BARTOLO', 'SAN BORJA', 'SAN ISIDRO', 'SAN JUAN DE LURIGANCHO', 'SAN JUAN DE MIRAFLORES', 'SAN LUIS', 'SAN MARTIN DE PORRES', 'SAN MIGUEL', 'SANTA ANITA', 'SANTA MARIA DEL MAR', 'SANTA ROSA', 'SANTIAGO DE SURCO', 'SURQUILLO', 'VILLA EL SALVADOR', 'VILLA MARIA DEL TRIUNFO'],
    'BARRANCA': ['BARRANCA', 'PARAMONGA', 'PATIVILCA', 'SUPE', 'SUPE PUERTO'],
    'CAJATAMBO': ['CAJATAMBO', 'CAJATAMBO', 'COPA', 'GORGOR', 'HUANCAPON', 'MANAS'],
    'CANTA': ['CANTA', 'ARAHUAY', 'HUAMANTANGA', 'HUAROS', 'LACHAQUI', 'SAN BUENAVENTURA', 'SANTA ROSA DE QUIVES'],
    'CAÑETE': ['SAN VICENTE DE CAÑETE', 'ASIA', 'CALANGO', 'CERRO AZUL', 'CHILCA', 'COAYLLO', 'IMPERIAL', 'LUNAHUANA', 'MALA', 'NUEVO IMPERIAL', 'PACARAN', 'QUILMANA', 'SAN ANTONIO', 'SAN LUIS', 'SANTA CRUZ DE FLORES', 'ZUÑIGA'],
    'HUARAL': ['HUARAL', 'ATAVILLOS ALTO', 'ATAVILLOS BAJO', 'AUCALLAMA', 'CHANCAY', 'IHUARI', 'LAMPIAN', 'PACARAOS', 'SAN MIGUEL DE ACOS', 'STA CRUZ DE ANDAMARCA', 'STA MARIA', 'SUMBILCA', 'VEINTISIETE DE NOVIEMBRE'],
    'HUAROCHIRÍ': ['MATUCANA', 'ANTIOQUIA', 'CALLAHUANCA', 'CARAMPOMA', 'CHICLA', 'HUANZA', 'HUAROCHIRI', 'LAHUAYTAMBO', 'LATA', 'SAN DAMIAN', 'SAN JUAN DE TANTARANCHE', 'SAN LORENZO DE QUINTI', 'SAN MATEO', 'SAN MATEO DE OTAO', 'SAN PEDRO DE CASTA', 'SAN PEDRO DE HUANCAYRE', 'SANGALLAYA', 'SANTA CRUZ DE COCACHACRA', 'STA EULALIA', 'STA LEONOR', 'STA RITA DE HUARANGAL', 'SANTO DOMINGO DE LOS OLLEROS', 'SURCO'],
    'HUAURA': ['HUACHO', 'AMBAR', 'CHECRAS', 'HUALMAY', 'HUAURA', 'LEONCIO PRADO', 'PACCHO', 'STA LEONOR', 'STA MARIA', 'SAYAN', 'VEGUETA'],
    'OYÓN': ['OYON', 'ANDAJES', 'CAUJUL', 'COCHAMARCA', 'NAVAN', 'OYON', 'PACHANGARA'],
    'YAUYOS': ['YAUYOS', 'ALIS', 'ALLAUCA', 'AYAVIRI', 'AZANGARO', 'CAÑETE', 'CHOCOS', 'COCHAS', 'COLONIA', 'HONGOS', 'HUAMPARA', 'HUANCAYA', 'HUANGASCAR', 'HUANTAN', 'HUAÑEC', 'LARAOS', 'LINCHA', 'MIRAFLORES', 'OMAS', 'QUINCHES', 'QUINOCAY', 'SAN JOAQUIN', 'SAN PEDRO DE PILAS', 'TANTA', 'TAURIPAMPA', 'TOMAS', 'TUPE', 'VIÑAC', 'VITIS', 'YAUYOS'],

    //provincias del departamento de LORETO
    'MAYNAS': ['IQUITOS', 'ALTO NANAY', 'FERNANDO LORES', 'INDIANA', 'LAS AMAZONAS', 'MAZAN', 'NAPO', 'PUNCHANA', 'PUTUMAYO', 'TORRES CAUSANA', 'BELÉN', 'SAN JUAN BAUTISTA'],
    'ALTO AMAZONAS': ['YURIMAGUAS', 'BALSAPUERTO', 'JEBEROS', 'LAGUNAS', 'SANTA CRUZ', 'TENIENTE CESAR LOPEZ ROJAS'],
    'LORETO': ['NAUTA', 'PARINARI', 'TIGRE', 'TROMPETEROS', 'URARINAS', 'PEBAS', 'RAMON CASTILLA'],
    'MARISCAL RAMÓN CASTILLA': ['REQUENA', 'ALTO TAPICHE', 'CAPARU', 'EMILIO SAN MARTIN', 'JENARO HERRERA', 'MAQUIA', 'PUINAHUA', 'SAQUENA', 'SOPLIN', 'TAPICHE', 'YAQUERANA', 'YURUA'],
    'PUTUMAYO': ['PUTUMAYO', 'PEVAS', 'SAN PABLO', 'YAQUERANA'],
  
    //provincias del departamento de MADRE DE DIOS 
    'TAMBOPATA': ['TAMBOPATA', 'INAMBARI', 'LAS PIEDRAS', 'LABERINTO'],
    'MANU': ['MANU', 'FITZCARRALD', 'MADRE DE DIOS', 'HUEPETUHE', 'INYAHUALLPA', 'LABERINTO', 'LAS PIEDRAS', 'TAMBOPATA'],
    'TAHUAMANU': ['TAHUAMANU', 'IÑAPARI'],

    //provincias del departamento de MOQUEGUA
    'MARISCAL NIETO': ['MOQUEGUA', 'CARUMAS', 'CUCHUMBAYA', 'SAMEGUA', 'SAN CRISTOBAL', 'TORATA'],
    'GENERAL SÁNCHEZ CERRO': ['OMATE', 'CHOJATA', 'COALAQUE', 'ICHUÑA', 'LA CAPILLA', 'LLOQUE', 'MATALAQUE', 'PUQUINA', 'QUINISTAQUILLAS', 'UBINAS', 'YUNGA'],
    'ILO': ['ILO', 'EL ALGARROBAL', 'PACOCHA'],
  
    //provincias del departamento de PASCO  
    'PASCO': ['PASCO', 'CHACAYAN', 'GOYLLARISQUIZGA', 'PAUCAR', 'SAN FRANCISCO DE ASÍS DE YARUSYACÁN', 'SIMON BOLÍVAR', 'TICLACAYÁN', 'VICCO', 'YANACANCHA'],
    'DANIEL ALCIDES CARRIÓN': ['YANAHUANCA', 'CHACAYAN', 'GOYLLARISQUIZGA', 'PAUCAR', 'SAN FRANCISCO DE ASÍS DE YARUSYACÁN', 'SIMON BOLÍVAR', 'TICLACAYÁN', 'VICCO', 'DANIEL ALCIDES CARRIÓN', 'YANACANCHA'],
    'OXAPAMPA': ['OXAPAMPA', 'CHONTABAMBA', 'HUANCABAMBA', 'PALCAZÚ', 'POZUZO', 'PUERTO BERMÚDEZ', 'VILLA RICA', 'CONSTITUCIÓN'],
  
    //provincias del departamento de PIURA
    'PIURA': ['PIURA', 'CASTILLA', 'CATACAOS', 'LA ARENA', 'LA UNIÓN', 'LAS LOMAS', 'TAMBOGRANDE', 'VEINTISEIS DE OCTUBRE'],
    'AYABACA': ['AYABACA', 'FRIAS', 'JILILI', 'LAGUNAS', 'MONTERO', 'PACAIPAMPA', 'PAIMAS', 'SAPILLICA', 'SICCHEZ', 'SUYO'],
    'HUANCABAMBA': ['HUANCABAMBA', 'CANCHAQUE', 'EL CARMEN DE LA FRONTERA', 'HUARMACA', 'LALAQUIZ', 'SAN MIGUEL DE EL FAIQUE', 'SONDOR', 'SONDORILLO', 'EL CARMEN DE LA FRONTERA', 'HUARANGO', 'SAN MIGUEL DE EL FAIQUE'],
    'MORROPÓN': ['CHULUCANAS', 'BUENOS AIRES', 'CHALACO', 'LA MATANZA', 'MORROPÓN', 'SALITRAL', 'SANTA CATALINA DE MOSSA', 'SANTO DOMINGO', 'YAMANGO'],
    'PAITA': ['PAITA', 'AMOTAPE', 'ARENAL', 'LA HUACA', 'COLAN', 'EL TALLAN', 'LA HUACA', 'TAMARINDO', 'VICHAYAL'],
    'SULLANA': ['SULLANA', 'BELLAVISTA', 'IGNACIO ESCUDERO', 'LANCONES', 'MARCABAL', 'MIGUEL CHECA', 'QUERECOTILLO', 'QUESMIL', 'SALITRAL', 'SAN JUAN DE BIGOTE', 'SANTA ROSA', 'SANTO DOMINGO', 'LA HUACA', 'TAMARINDO', 'VICHAYAL'],
    'TALARA': ['TALARA', 'EL ALTO', 'LA BREA', 'LOBITOS', 'LOS ORGANOS', 'MANCORA', 'PARINAS'],

    //provincias del departamento de PUNO
    'PUNO': ['PUNO', 'ACORA', 'AMANTANI', 'ATUNCOLLA', 'CAPACHICA', 'CHUCUITO', 'COATA', 'HUATA', 'MAÑAZO', 'PAUCARCOLLA', 'PICHACANI', 'PLATERIA', 'SAN ANTONIO', 'TIQUILLACA', 'VILQUE'],
    'AZÁNGARO': ['AZÁNGARO', 'ACHAYA', 'ARAPA', 'ASILLO', 'CAMINACA', 'CHUPA', 'JOSE DOMINGO CHOQUEHUANCA', 'MUÑANI', 'POTONI', 'SAMAN', 'SAN ANTON', 'SAN JOSÉ', 'SAN JUAN DE SALINAS', 'SAN PEDRO DE PUTINA PUNCO', 'SANTIAGO DE PUPUJA', 'TIRAPATA'],
    'CARABAYA': ['MACUSANI', 'AJOYANI', 'AYAPATA', 'COASA', 'CORANI', 'CRUCERO', 'ITUATA', 'OLLACHEA', 'SAN GABAN', 'USICAYOS'],
    'CHUCUITO': ['JULI', 'DESAGUADERO', 'HUACULLANI', 'KELLUYO', 'PISACOMA', 'POMATA', 'ZEPITA'],
    'EL COLLAO': ['ILAVE', 'CAPAZO', 'CONDURIRI', 'PILCUYO', 'SANTA ROSA', 'CONDURIRI', 'PILCUYO', 'SANTA ROSA'],
    'HUANCANÉ': ['HUANCANÉ', 'COJATA', 'HUATASANI', 'INCHUPALLA', 'PUSI', 'ROSASPATA', 'TARACO', 'VILQUE CHICO', 'VILQUE GRANDE'],
    'LAMPA': ['LAMPA', 'CALAPUJA', 'NICASIO', 'OCUVIRI', 'PALCA', 'PARATIA', 'PUCARA', 'SANTA LUCIA', 'VILAVILA'],
    'MELGAR': ['AYAVIRI', 'ANTAUTA', 'CUPI', 'LLALLI', 'MACARI', 'NUÑOA', 'ORURILLO', 'SANTA ROSA', 'UMACHIRI'],
    'MOHO': ['MOHO', 'CONIMA', 'HUAYRAPATA', 'TILALI', 'HUAYRAPATA', 'TILALI'],
    'SAN ANTONIO DE PUTINA': ['PUTINA', 'ANANEA', 'PEDRO VILCA APAZA', 'QUILCAPUNCU', 'SINA'],
    'SAN ROMÁN': ['JULIACA', 'CABANA', 'CABANILLAS', 'CARACOTO', 'SAN MIGUEL', 'SAN MIGUEL'],
    'SANDIA': ['SANDIA', 'ALTO INAMBARI', 'CUYOCUYO', 'LIMBANI', 'PATAMBUCO', 'PHARA', 'QUIACA', 'SAN JUAN DEL ORO', 'YANAHUAYA', 'CUYOCUYO', 'LIMBANI', 'PATAMBUCO', 'PHARA', 'QUIACA', 'SAN JUAN DEL ORO', 'YANAHUAYA'],
    'YUNGUYO': ['YUNGUYO', 'ANAPIA', 'COPANI', 'CUTURAPI', 'OLLARAYA', 'TINICACHI', 'UNICACHI'],

    //provincias del departamento de SAN MARTIN
    'MOYOBAMBA': ['MOYOBAMBA', 'CALZADA', 'HABANA', 'JEPELACIO', 'SORITOR', 'YANTALO', 'CLOVER', 'HERNÁN VIDAL'],
    'BELLAVISTA': ['BELLAVISTA', 'ALTO BIAVO', 'BAJO BIAVO', 'HUALLAGA', 'SAN PABLO', 'SAN RAFAEL'],
    'EL DORADO': ['SAN JOSÉ DE SISA', 'AGUA BLANCA', 'SAN MARTÍN', 'SANTA ROSA', 'SHATOJA'],
    'HUALLAGA': ['SAPOSOA', 'ALTO SAPOSOA', 'EL ESLABÓN', 'PINGOY', 'TINGO DE SAPOSOA', 'NUEVO LIMÓN', 'SAPOSOA', 'ALTO SAPOSOA', 'EL ESLABÓN', 'PINGOY', 'TONGOY'],
    'LAMAS': ['LAMAS', 'ALONSO DE ALVARADO', 'BARRANQUITA', 'CAYNARACHI', 'CUÑUMBUQUI', 'PINTO RECODO', 'RUMISAPA', 'SAN ROQUE DE CUMBAZA', 'SHANAO', 'TABALOSOS', 'ZAPATERO'],
    'MARISCAL CÁCERES': ['JUANJUÍ', 'CAMPANILLA', 'HUICUNGO', 'PACHIZA', 'PAJARILLO', 'TINGO DE PONASA', 'GUAYABAL', 'JUAN GUERRA', 'LEONCIO PRADO', 'MARIANO DAMASO BERAUN', 'HUICUNGO', 'PACHIZA', 'PAJARILLO', 'TINGO DE PONASA'],
    'PICOTA': ['PICOTA', 'BuenOS AIRES', 'CASPISAPA', 'PICOTA', 'PILLUANA', 'PUCACACA', 'SAN CRISTOBAL', 'UCHIZA'],
    'RÍOJA': ['RÍOJA', 'AWAJUN', 'ELÍAS SOPLÍN VARGAS', 'NUEVO PROGRESO', 'PARDO MIGUEL', 'POSIC', 'SACRAMENTO', 'SHUNTE', 'YAQUERANA', 'YORONGOS', 'NUEVO PROGRESO', 'POSIC', 'RÍOJA'],
    'SAN MARTÍN': ['SAN MARTÍN', 'SAPOSOA', 'ALTO SAPOSOA', 'EL ESLABÓN', 'PINGOY', 'TONGOY'],
    'TOCACHE': ['TOCACHE', 'NUEVA CAJAMARCA', 'POLVORINOS', 'SHUNTE', 'TACABAMBA', 'TINGO DE PONASA', 'TUNUNTUNUMA', 'TOCACHE', 'NUEVA CAJAMARCA', 'POLVORINOS', 'SHUNTE', 'TACABAMBA', 'TINGO DE PONASA', 'TUNUNTUNUMA'],

    //provincias del departamento de TACNA  
    'TACNA': ['TACNA', 'ALTO DE LA ALIANZA', 'CALANA', 'CIUDAD NUEVA', 'INCLAN', 'PACHIA', 'PALCA', 'POCOLLAY', 'SAMA', 'CORONEL GREGORIO ALBARRACIN LANCHIPA', 'LA YARADA-LOS PALOS'],
    'CANDARAVE': ['CANDARAVE', 'CAIRANI', 'CAMILACA', 'CANDARAVE', 'CURIBAYA', 'HUANUARA', 'QUILAHUANI'],
    'JORGE BASADRE': ['LOCUMBA', 'ILABAYA', 'ITE'],
    'TARATA': ['TARATA', 'ESTIQUE', 'ESTIQUE PAMPA', 'SITAJARA', 'SUSAPAYA', 'TARUCACHI', 'TICACO', 'TARATA', 'HEROES ALBARRACIN'],
  
  
    //provincias del departamento de TUMBES
    'TUMBES': ['TUMBES', 'CORRALES', 'LA CRUZ', 'PAMPAS DE HOSPITAL', 'SAN JACINTO', 'SAN JUAN DE LA VIRGEN'],
    'CONTRALMIRANTE VILLAR': ['ZORRITOS', 'CASITAS', 'CANOAS DE PUNTA SAL', 'ZORRITOS'],
    'ZARUMILLA': ['ZARUMILLA', 'AGUAS VERDES', 'MATAPALO', 'PAPAYAL'],

    //provincias del deparamento de UCAYALI
    'CORONEL PORTILLO': ['CALLERIA', 'CAMPOVERDE', 'IPARIA', 'MASISEA', 'YARINACOCHA', 'NUEVA REQUENA', 'MANANTAY'],
    'ATALAYA': ['RAYMONDI', 'SEPAHUA', 'TAMAYO', 'YURUA'],
    'PADRE ABAD': ['PADRE ABAD', 'IRAZOLA', 'CURIMANA', 'NESHUYA'],
    'PURÚS': ['PURUS', 'PURÚS'],

   
  };


  constructor() { }


  getDepartamentos(): string[] {
    return this.departamentos;
  }

  getProvinciasPorDepartamento(departamento: string): string[] {
    return this.provinciasPorDepartamento[departamento] || [];
  }

  getDistritosPorProvincia(provincia: string): string[] {
    return this.distritosPorProvincia[provincia] || [];
  }
}
