import { Component, OnInit } from '@angular/core';
import { Router ,ActivatedRoute} from '@angular/router';
import { ExpedienteService } from 'src/app/servicios/expediente/expediente.service';
import { ParteService } from 'src/app/servicios/parte/parte.service';
import { DatosCompartidosService } from 'src/app/servicios/datoslogin/datos-compartidos.service';
import { SafeResourceUrl, DomSanitizer } from '@angular/platform-browser';
import { IndizacionService } from 'src/app/servicios/indizacion/indizacion.service';
import { DigitalizacionService } from 'src/app/servicios/digitalizacion/digitalizacion.service';
import Swal from 'sweetalert2';
declare var bootstrap: any;
@Component({
  selector: 'app-indizador-expediente-form',
  templateUrl: './indizador-expediente-form.component.html',
  styleUrls: ['./indizador-expediente-form.component.css']
})
export class IndizadorExpedienteFormComponent implements OnInit{
 
  dataIndizacion:any = [];

 
  constructor(private digitalizacionService:DigitalizacionService,private indizacionService:IndizacionService,private sanitizer: DomSanitizer,private activatedRoute:ActivatedRoute,private router:Router, private expedienteService:ExpedienteService, private parteService:ParteService, private datosCompartidosService:DatosCompartidosService ){}
  detalleExpediente:any=[]//contempla todos los detalles que corresponde al expediente de presentación 
  observacionDigitalizado:string=''
  data_expediente:any={
    id_inventario: null,
    id_responsable: null,
    nombre_expediente: null,
    fojas: null,
    fojas_unacara: null,
    fojas_doscaras: null,
    fojas_obs: null,
    copias_originales: null,
    copias_simples: null,
    observaciones: null,
    lote: null,
    estado_preparado:true,
    estado_digitalizado: null,
    estado_indizado: null,
    estado_controlado: null,
    estado_fedatado:null  
}

listaTempDemanantes:any=[]//[]//lista temporal de demandantes
listaTempDemandados:any=[]// lista temporal de demandador
// listaTempIndizacion:any=[]//lista indizacion
datalistMateria: string[] = [
  'ABANDONO DE MENORES',
'ABANDONO MATERIAL, PELIGRO MORAL Y MALTRATOS',
'ABUSO DE DERECHO',
'ACCESION',
'ACCION CONTENCIOSA ADMINISTRATIVA',
'ACCION DE AMPARO',
'ACCION DE CUMPLIMIENTO',
'ACCION DE DISOLUCION DE SINDICATO',
'ACCION DE GARANTIA',
'ACCION DE INCONSTITUCIONALIDAD',
'ACCION DE INCUMPLIMIENTO',
'ACCION DE REPETICION',
'ACCION DECLARATIVA DE PRESC. DE DERECHOS. Y BENEF. LABORALES',
'ACCION ESTIMATORIA',
'ACCION POPULAR',
'ACCION POSESORIA',
'ACCION RECISORIA',
'ACCION REVOCATORIA',
'ACCION SUBROGATORIA',
'ACEPTACION DE ALBACEA',
'ACLARACION, CORRECION, MODIFICACION DOCUMENTAL',
'ACUERDO JUNTA DE ACREEDORES',
'ADICION DE NOMBRE',
'ADMINISTRACION JUDICIAL DE BIENES',
'ADMINISTRACION JUDICIAL DE BIENES DE MENOR DE EDAD',
'ADOPCION',
'ADQUISICION DE PROPIEDAD',
'AFP',
'AGRESIONES VERBALES',
'ALIMENTOS',
'ANTICIPO DE HERENCIA',
'ANTICIPO DE LEGITIMA',
'ANULABILIDAD DE ACTO JURIDICO',
'ANULABILIDAD DE MATRIMONIO',
'ANULACION DE DECLARATORIA DE FABRICA',
'ANULACION DE LAUDOS ARBITRALES',
'ANULACION DEL LAUDO ARBITRAL INTERNACIONAL',
'APELACION',
'APELACION DE AUTO',
'APELACION DE LAUDO ARBITRAL',
'APELACION DE SENTENCIA',
'APERTURA DE TESTAMENTO',
'APROBACION JUDICIAL DE PARTICION CONVENCIONAL',
'ARRENDAMIENTO FINANCIERO',
'ARTICULO 160 C.N.A. CODIGO DEL NINO Y ADOLESCENTE',
'ASIGNACION ANTICIPADA DE ALIMENTOS',
'ATENCION INTEGRAL',
'AUDIENCIA DE CONCILIACION',
'AUMENTO DE ALIMENTOS',
'AUTORIZ. PARA DISPONER BIENES DE AUSENTES',
'AUTORIZACION DE DESCERRAJE Y/O SIMILARES',
'AUTORIZACION DE FIRMA DE NOTARIO',
'AUTORIZACION DE MATRIMONIO DE MENOR',
'AUTORIZACION DE VIAJE DE MENOR',
'AUTORIZACION JUDICIAL',
'AUTORIZACION JUDICIAL PARA DISPONER BIEN DEL MENOR',
'AUTORIZACION PARA DISPONER DERECHOS DE INCAPACES',
'AUTORIZACION PARA RETORNAR AL HOGAR CONYUGAL',
'AUXILIO JUDICIAL',
'CADUCIDAD',
'CADUCIDAD DE DERECHO',
'CADUCIDAD DE TESTAMENTO',
'CALCULO DE PENSION DE JUBILACION',
'CALIFICACION DE BIEN SOCIAL',
'CALIFICACION DE DESPIDO',
'CAMBIO DE DENOMINACION O RAZON SOCIAL',
'CAMBIO DE NOMBRE, SUPRESION DE NOMBRE Y/O ADICION DE NOMBRE',
'CAMBIO DE TITULAR SERVICIO TELEFONICO',
'CAMBIO EN LA FORMA DE PRESTAR ALIMENTOS',
'CANCELACION DE ANTICRESIS',
'CANCELACION DE ASIENTO REGISTRAL',
'CANCELACION DE GRAVAMENES',
'CANCELACION DE HIPOTECA',
'CANCELACION DEL TITULO DE PROPIEDAD',
'CANCELACION Y EXCLUSION DE SOCIO',
'CERTIFICADO DE SUPERVIVENCIA (LEY 26002 MODIFICADO PO LEY 26883)',
'CESACION DE USO INDEBIDO DE NOMBRE',
'CESE DE ACTOS DE HOSTIGAMIENTO SEXUAL',
'CESE DE ACTOS DE HOSTILIDAD DEL EMPLEADOR',
'CESE DE ACTUACION MATERIAL',
'CESE DE VIOLENCIA FAMILIAR',
'CLAUSURA DE SERVIDUMBRE',
'COBRO DE DINERO',
'COBRO DE HONORARIOS PROFESIONALES',
'COBRO DE REMUNERACIONES',
'COLACION DE HERENCIA',
'COLOCACION FAMILIAR',
'COMPETENCIAL',
'COMPROBACION DE TESTAMENTO',
'CONCEJO DE FAMILIA',
'CONFIRMACION DE ACTO JURIDICO',
'CONFIRMACION DE MATRIMONIO DE MENOR DE EDAD',
'CONFLICTO DE COMPETENCIA O ATRIBUCIONES',
'CONFLICTOS INTRA E INTERSINDICALES',
'CONFORMACION Y FUNCIONAMIENTO DEL CONSEJO DE FAMILIA',
'CONSEJO DE FAMILIA',
'CONSIGNACION',
'CONSIGNACION DE CUOTA SINDICAL',
'CONSIGNACION DE PENSION ALIMENTICIA',
'CONSIGNACIONES LABORALES POR PAGO DE CUOTA SINDICAL',
'CONSTITUCION DE PATRIMONIO FAMILIAR',
'CONSTITUCION DE PATRIMONIO FAMILIAR DE MENOR',
'CONTENCIOSO',
'CONTIENDA DE COMPETENCIA INTERNACIONAL PRIVADO',
'CONTRADICCION DE DESHEREDACION',
'CONTRADICCION DE SENTENCIA',
'CONTRAVENCION',
'CONTRAVENCION AL CODIGO DE LOS NIÑOS Y ADOLESCENTES',
'CONTROL Y COLABORACION JUDICIAL PARA ACTUACION DE PRUEBAS',
'CONVOCATORIA A ELECCIONES',
'CONVOCATORIA A JUNTA DE ACCIONISTAS',
'CONVOCATORIA A JUNTA O ASAMBLEA GENERAL',
'CONVOCATORIA A JUNTA O ASAMBLEA GENERAL - SOCIEDAD ANONIMA',
'CONVOCATORIA A JUNTA O ASAMBLEA GENERAL - SOCIEDAD ANONIMA ABIERTA',
'CONVOCATORIA A JUNTA O ASAMBLEA GENERAL - SOCIEDAD ANONIMA CERRADA',
'CONVOCATORIA A JUNTA O ASAMBLEA GENERAL - SOCIEDAD CIVIL',
'CONVOCATORIA A JUNTA O ASAMBLEA GENERAL - SOCIEDAD COLECTIVA',
'CONVOCATORIA A JUNTA O ASAMBLEA GENERAL - SOCIEDAD COMERCIAL DE RESPONSABILIDAD LIMITADA',
'CONVOCATORIA A JUNTA O ASAMBLEA GENERAL - SOCIEDAD EN COMANDITA',
'CONVOCATORIA JUDICIAL',
'CREDITOS LABORALES',
'CUMPLIMIENTO',
'CUMPLIMIENTO DE ACTO ADMINISTRATIVO FIRME',
'CUMPLIMIENTO DE ACTUACION ADMINISTRATIVA',
'CUMPLIMIENTO DE CONTRATO',
'CUMPLIMIENTO DE CONTRATO MERCANTIL',
'CUMPLIMIENTO DE FORMALIDAD DE TITULO EJECUTIVO',
'CUMPLIMIENTO DE OBLIGACON DE PAGO',
'CUMPLIMIENTO DE RESOLUCION ADMINISTRATIVA',
'CURATELA',
'DAÑO MINIMO',
'DECL. DE INCAPACIDAD FISICA PARA EL TRABAJO',
'DECL. DESAPARICION, AUSENCIA O MUERTE PRESUNTA',
'DECLARACION CONTRARIA A DERECHO',
'DECLARACION DE AUSENCIA',
'DECLARACION DE BIEN COMUN',
'DECLARACION DE BIEN PROPIO',
'DECLARACION DE CONTRARIA A DERECHO',
'DECLARACION DE DERECHO DE PROPIEDAD',
'DECLARACION DE DESAPARICION',
'DECLARACION DE HEREDEROS',
'DECLARACION DE MUERTE PRESUNTA',
'DECLARACION DE NULIDAD DE ACTO ADMINISTRATIVO',
'DECLARACION DE NULIDAD TOTAL O PARCIAL Ó INEFICACIA DE ACTOS ADMINISTRATIVOS',
'DECLARACION DE PATERNIDAD',
'DECLARACION DE PROPIEDAD',
'DECLARACION DE PROPIEDAD POR PRESCIPCION',
'DECLARACION DE RELACION CONTRACTUAL',
'DECLARACION DE SOLTERIA',
'DECLARACION DE UNION DE HECHO',
'DECLARACION DE VALIDEZ DE MATRIMONIO',
'DECLARACION JUDICIAL',
'DECLARACION JUDICIAL DE CONVIVENCIA',
'DECLARACION JUDICIAL DE INCAPACIDAD IRREVERSIBLE',
'DECLARACION JUDICIAL DE PATERNIDAD EXTRAMATRIMONIAL',
'DECLARACION JUDICIAL DE PROPIEDAD POR PRESCRIPCION',
'DECLARATORIA DE HEREDEROS',
'DELIMITACION DE AREAS Y LINDEROS',
'DEMOLICION',
'DEPOSITO',
'DERECHO DE ADQUISICION PREFERENTE DE ACCIONES',
'DERECHO DE OPOSICION A FUSION O ESCISION',
'DERECHOS LABORALES',
'DESAFECTACION',
'DESALOJO',
'DESAPROBACION DE RENDICION DE CUENTAS',
'DESCRIPCION',
'DESHAUCIO',
'DESHEREDACION',
'DESIGNACION DE ARBITROS',
'DESIGNACION DE CURADOR',
'DESIGNACION DE LIQUIDADORES',
'DESIGNACION JUDICIAL',
'DESLINDE',
'DESPIDO ARBITRARIO',
'DETERMINACION DE SALDO DEUDOR',
'DILIGENCIA PREPARATORIA',
'DISCERNIMIENTO DEL CARGO DE GUARDADOR',
'DISOLUCION Y LIQUIDACION DE SOCIEDADES',
'DISOLUSION DE ASOCIACION',
'DISPENSA JUDICIAL DE DOCUMENTOS',
'DISPENSA JUDICIAL PARA PRESENTAR DOCUMENTOS PARA MATRIMONIO',
'DIVISION Y PARTICION',
'DIVISION Y PARTICION EXTRAJUDICIAL',
'DIVISION Y PARTICIPACION DE BIENES',
'DIVORCIO POR CAUSAL',
'DUPLICADO DE TITULO PROFESIONAL',
'EJECUCION COACTIVAS',
'EJECUCION DE ACTA DE CONCILIACION',
'EJECUCION DE ACTA DE VIOLENCIA FAMILIAR',
'EJECUCION DE ACTA SUSCRITA ENTRE TRABAJADOR Y EMPLEADOR ANTE AUTORIDAD ADMINISTRATIVA DE TRABAJO',
'EJECUCION DE ACTAS',
'EJECUCION DE ACUERDO',
'EJECUCION DE ACUERDO CONCILIATORIO EN VIOLENCIA FAMILIAR',
'EJECUCION DE CONTRATO',
'EJECUCION DE GARANTIAS',
'EJECUCION DE LAUDOS ARBITRALES',
'EJECUCION DE LAUDOS EXTRANJEROS RECONOCIDOS',
'EJECUCION DE LIQUIDACION PARA COBRANZA DE APORTES DEL SISTEMA PRIVADO DE PENSIONES',
'EJECUCION DE OBLIGACIONES',
'EJECUCION DE RESOLUCION ADMINISTRATIVA',
'EJECUCION DE RESOLUCIONES JUDICIALES',
'EJECUCION DE SENTENCIA',
'EJECUCION FORZADA ADJUDICACION',
'EJECUCION FORZADA DE PAGO',
'EJECUCION FORZADA REMATE',
'EJECUTIVO DE ACTAS DE CONCILIACION CELEBRADAS ANTE EL MINISTERIO DE TRABAJO',
'ENDOSE DE CONSIGNACION',
'ENRIQUECIMIENTO INDEBIDO',
'ENRIQUECIMIENTO SIN CAUSA',
'ENTREGA DE BIENES',
'ENTREGA DE CERTIFICADO DE TRABAJO',
'ENTREGA, CANC. O REDENC. DE OTROS DOC. QUE CONTENGAN DERECHO',
'ENTREGA, CANCELACION O REDENCION DE ACCIONES',
'ENTREGA, CANCELACION O REDENCION DE CERTIFICADOS',
'ENTREGA, CANCELACION O REDENCION DE POLIZAS',
'ESTABLECIMIENTO DE SERVIDUMBRE',
'EXCEPCION',
'EXCLUSION DE HERENCIA',
'EXCLUSION DE NOMBRES',
'EXCLUSION DE PROPIEDAD',
'EXCLUSION DE SOCIO - SOCIEDAD ANONIMA',
'EXCLUSION DE SOCIO - SOCIEDAD ANONIMA ABIERTA',
'EXCLUSION DE SOCIO - SOCIEDAD ANONIMA CERRADA',
'EXCLUSION DE SOCIO - SOCIEDAD CIVIL',
'EXCLUSION DE SOCIO - SOCIEDAD COMERCIAL DE RESPONSABILIDAD LIMITADA',
'EXCLUSION DE SOCIO EN SOCIEDAD COLECTIVA',
'EXCLUSION DE SOCIO EN SOCIEDAD EN COMANDITA',
'EXCLUSION DE SOCIOS / EXPULSION DE ASOCIADOS',
'EXCLUSION, INCLUSION DE BIEN',
'EXEQUATUR',
'EXHORTO',
'EXONERACION DE ALIMENTOS',
'EXONERACION Y EXTINSION DE ALIMENTOS',
'EXPROPIACION',
'EXPULSION DE ASOCIADOS',
'EXTINCION DE ALIMENTOS',
'EXTINCION DE GARANTIA',
'EXTINCION DE PATRIMONIO FAMILIAR',
'EXTINCION DE RESPONSABILIDAD SOCIAL FRENTE A ACREEDORES SIN PAGOS',
'FACCION DE INVENTARIO',
'FALTA CONTRA EL INTERES PUBLICO',
'FALTA CONTRA EL PATRIMONIO',
'FALTA CONTRA LA PERSONA',
'FALTA CONTRA LA SEGURIDAD PUBLICA',
'FALTA CONTRA LA TRANQUILIDAD PUBLICA',
'FALTA CONTRA LAS BUENAS COSTUMBRES',
'FIJACION DE ALIMENTOS',
'FILIACION',
'FILIACION - IMP. DE PATERNIDAD',
'FILIACION EXTRAMATRIMONIAL',
'FILIACION MATRIMONIAL',
'FORMACION DE CONSEJO DE FAMILIA PARA NOMBRAR CURADOR',
'GUARDA DE LOS BIENES DE AUSENTE',
'GUARDA DE MENOR',
'HABEAS CORPUS',
'HABEAS DATA',
'HOSTILIZACION',
'HURTO',
'IMCUMPLIMIENTO Y PAGO DE CONSTRUCCION',
'IMCUPLIMIENTO DE CONTRATO',
'IMCUPLIMIENTO DE CONTRATO MERCANTIL',
'IMPUG. DE ACTAS DE CONC. CELEBRADAS ANTE AUTOR. ADM. DE TRAB',
'IMPUGNACION DE REGLAMENTO INTERNO DE TRABAJO',
'IMPUGNACION A HERENCIA',
'IMPUGNACION DE ACTO O RESOLUCION ADMINISTRATIVA',
'IMPUGNACION DE ACUERDO DE UNA ASOCIACION CIVIL',
'IMPUGNACION DE ACUERDO SOCIETARIO',
'IMPUGNACION DE ACUERDOS',
'IMPUGNACION DE ACUERDOS DE ASAMBLEA DE OBLIGACIONISTAS',
'IMPUGNACION DE ACUERDOS DE EXCLUSION DE ACCIONISTAS',
'IMPUGNACION DE ACUERDOS DE JUNTA GENERAL DE ACCIONISTAS',
'IMPUGNACION DE ACUERDOS POR DEFECTO DE FORMA',
'IMPUGNACION DE DESPIDO',
'IMPUGNACION DE DESPIDO ARBITRARIO',
'IMPUGNACION DE ESTATUTOS SINDICALES',
'IMPUGNACION DE FILIACION',
'IMPUGNACION DE LAS SANCIONES DISCIPLINARIAS IMPUESTAS POR EL EMPLEADOR',
'IMPUGNACION DE MATERNIDAD',
'IMPUGNACION DE MATERNIDAD-PATERNIDAD',
'IMPUGNACION DE PARTIDA DE NACIMIENTO(J.C.)',
'IMPUGNACION DE PATERNIDAD',
'IMPUGNACION DE PATERNIDAD EXTRAMATRIMONIAL',
'IMPUGNACION DE RECONOCIMIENTO',
'IMPUGNACION DE RENUNCIA DE HERENCIA',
'IMPUGNACION DE RESOLUCION',
'IMPUGNACION DE TRANSFERENCIA DE TITULOS Y VALORES DISTINTO AL ENDOSO',
'IMPUGNACION NULIDAD E INEFICACIA DE TITULO DE VALOR',
'IMPUGNACION O NULIDAD DE ACUERDOS DE JUNTA GENERAL',
'IMPUGNACION/CONTESTACION/NEGACION DE PATERNIDAD',
'INAPLICACION DE NORMA',
'INCAUTACION DE BIEN MUEBLE',
'INCIDENTE DE HONORARIOS PROFESIONALES',
'INCLUSION DE BIEN INMUEBLE',
'INCLUSION DE HERENCIA',
'INCUMPLIMIENTO DE CONTRATO',
'INCUMPLIMIENTO DE DISPOSICIONES CONVENCIONALES',
'INCUMPLIMIENTO DE DISPOSICIONES LEGALES',
'INCUMPLIMIENTO DE DISPOSICIONES Y NORMAS LABORALES',
'INCUMPLIMIENTO DE PAGO DE RENTA POR ARRENDAMIENTO',
'INCUMPLIMIENTO Y PAGO DE CONSTRUCCION',
'INDEM. POR DAÑOS Y PERJUICIOS POR FALTA GRAVE DEL TRABAJADOR',
'INDEM. POR DAÑOS Y PERJUICIOS POR INCUMP. DE CONTRATO',
'INDEM. POR DAÑOS Y PERJUICIOS POR INCUMP. DE NORMAS LABORAL',
'INDEMNIZACION',
'INDEMNIZACION POR DAÑOS Y PERJUICIOS',
'INDEMNIZACION POR DESPIDO ARBITRARIO Y OTROS',
'INDEMNIZACION POR DETENCION ARBITRARIA',
'INDEMNIZACION POR INCUMPLIMIENTO DE OBLIGACIONES',
'INDEMNIZACION POR INCUMPLIMIENTO DE RESPONSABLES',
'INDEMNIZACION-TRANSITO (CUANTIA HASTA 100 URP)',
'INDEMNIZACIÓN COMO PRETENSIÓN ACCESORIA',
'INEFICACIA DE ACTO JURIDICO',
'INEFICACIA DE RESOLUCION O ACTO ADMINSITRATIVO',
'INEFICACIA DE TITULO VALOR',
'INFRACCION A LA LEY PENAL',
'INFRACCION CONTRA EL ESTADO Y LA DEFENSA NACIONAL',
'INFRACCION CONTRA EL HONOR',
'INFRACCION CONTRA EL ORDEN ECONOMICO',
'INFRACCION CONTRA EL ORDEN FINANCIERO Y MONETARIO',
'INFRACCION CONTRA EL PATRIMONIO',
'INFRACCION CONTRA EL PATRIMONIO CULTURAL',
'INFRACCION CONTRA LA ADMINISTRACION PUBLICA',
'INFRACCION CONTRA LA CONFIANZA Y LA BUENA FE EN LOS NEGOCIOS',
'INFRACCION CONTRA LA ECOLOGIA',
'INFRACCION CONTRA LA FAMILIA',
'INFRACCION CONTRA LA FE PUBLICA',
'INFRACCION CONTRA LA HUMANIDAD',
'INFRACCION CONTRA LA LIBERTAD',
'INFRACCION CONTRA LA LIBERTAD SEXUAL',
'INFRACCION CONTRA LA SALUD PUBLICA',
'INFRACCION CONTRA LA SEGURIDAD PUBLICA',
'INFRACCION CONTRA LA TRANQUILIDAD PUBLICA',
'INFRACCION CONTRA LA VIDA, EL CUERPO Y LA SALUD',
'INFRACCION CONTRA LA VOLUNTAD POPULAR',
'INFRACCION CONTRA LOS DERECHOS INTELECTUALES',
'INFRACCION CONTRA LOS PODERES DEL ESTADO Y EL ORDEN CONSTITUCIONAL',
'INFRACCION TRIBUTARIA',
'INHIBITORIA',
'INMATRICULACION DE VEHICULO MOTORIZADO',
'INSCRIPCION',
'INSCRIPCION DE PARTIDA',
'INSCRIPCION DE REGISTRO',
'INSCRIPCION DE VEHICULO',
'INSCRIPCION REGISTRAL',
'INSCRIPCION Y RECTIFICACION DE PARTIDA',
'INSPECCION JUDICIAL',
'INTERDICCION',
'INTERDICCION DE MENORES',
'INTERDICTO',
'INTERVENCION',
'INVALIDEZ DE MATRIMONIO',
'INVENTARIO',
'INVENTARIO DE BIENES',
'INVENTARIO DE BIENES DE MENOR DE EDAD',
'INVENTARIO JUDICIAL',
'INVESTIGACION TUTELAR',
'JUSTIFICACION DE DESHEREDACION',
'LESIONES CULPOSAS',
'LESIONES DOLOSAS',
'LEVANTAMIENTO DE HIPOTECA',
'LEY GENERAL DE ARBITRAJE',
'LICENCIA PARA ENAJENAR U OBLIGAR BIENES DE MENORES',
'LIMITACION AL CONYUGE DE LA ADMIN. DE BIENES DE LA SOCIEDAD',
'LIQUIDACION DE BIENES DE LA SOCIEDAD DE GANANCIALES',
'LOCACION DE SERVICIOS',
'MATERIAS DEL SISTEMA DE PENSIONES',
'MEDIDA CAUTELAR',
'MEDIDA CAUTELAR DE ANOTACION DE DEMANDA',
'MEDIDA CAUTELAR DE ANOTACION DE DEMANDA EN REGISTRO PUBLICOS',
'MEDIDA CAUTELAR DE EMBARGO',
'MEDIDA CAUTELAR DE EMBARGO EN FORMA DE ADMINISTRACION DE BIENES',
'MEDIDA CAUTELAR DE EMBARGO EN FORMA DE DEPOSITO',
'MEDIDA CAUTELAR DE EMBARGO EN FORMA DE INSCRIPCION',
'MEDIDA CAUTELAR DE EMBARGO EN FORMA DE INTERVENCION',
'MEDIDA CAUTELAR DE EMBARGO EN FORMA DE RETENCION',
'MEDIDA CAUTELAR DE EMBARGO EN FORMA DE SECUESTRO',
'MEDIDA CAUTELAR DENTRO DEL PROCESO',
'MEDIDA CAUTELAR FUERA DEL PROCESO',
'MEDIDA CAUTELAR GENERICA',
'MEDIDA CAUTELAR INNOVATIVA',
'MEDIDA CAUTELAR NO INNOVATIVA',
'MEDIDA CAUTELAR PARA FUTURA EJECUCION FORZADA',
'MEDIDA CAUTELAR TEMPORAL SOBRE EL FONDO',
'MEDIDAS DE PROTECCION',
'MEDIDAS DISCIPLINARIAS',
'MEJOR DERECHO A LA POSESION',
'MEJOR DERECHO A LA PROPIEDAD',
'MENOR CUANTIA',
'MODIFICACION DE DENOMINACION O RAZON SOCIAL',
'NECESIDAD Y UTILIDAD',
'NOMBRAMIENTO DE ADMINISTRACION JUDICIAL',
'NOMBRAMIENTO DE ADMINISTRADOR DE BIENES',
'NOMBRAMIENTO DE ALBACEA',
'NOMBRAMIENTO DE CURADOR',
'NULIDAD',
'NULIDAD DE ABSORCION DE SOCIEDADES',
'NULIDAD DE ACTA DE ESCLARECIMIENTO',
'NULIDAD DE ACTO JURIDICO',
'NULIDAD DE ACUERDO',
'NULIDAD DE ASIENTO REGISTRAL',
'NULIDAD DE CONTRATO',
'NULIDAD DE CONTRATO DE AFILIACION',
'NULIDAD DE CONTRATO MERCANTIL',
'NULIDAD DE CONVOCATORIA',
'NULIDAD DE COSA JUZGADA FRAUDULENTA',
'NULIDAD DE DESPIDO',
'NULIDAD DE DOCUMENTOS',
'NULIDAD DE ESCISION DE SOCIEDADES',
'NULIDAD DE ESCRITURA PUBLICA',
'NULIDAD DE FUSION DE SOCIEDADES',
'NULIDAD DE HIPOTECAS',
'NULIDAD DE INCORPORACION',
'NULIDAD DE JUNTA DE ACCIONISTAS',
'NULIDAD DE LAUDO ARBITRAL',
'NULIDAD DE MATRIMONIO',
'NULIDAD DE OBLIGACION ALIMENTARIA',
'NULIDAD DE PACTO SOCIAL',
'NULIDAD DE PARTIDA',
'NULIDAD DE RESOLUCION ADMINISTRATIVA',
'NULIDAD DE RESOLUCION Y TITULOS DE PROPIEDAD',
'NULIDAD DE RESOLUCIÓN O ACTO ADMINISTRATIVO',
'NULIDAD DE SEPARACION Y RETIRO DE SOCIOS',
'NULIDAD DE TESTAMENTO',
'NULIDAD DE TITULO VALOR',
'NULIDAD DE TRANSFORMACION DE SOCIEDADES',
'NULIDAD DE TRANSMISION DE PARTICIPACIONES',
'NULIDAD DEL MATRIMONIO',
'OBLIGACION DE DAR',
'OBLIGACION DE DAR BIEN MUEBLE',
'OBLIGACION DE DAR SUMA DE DINERO',
'OBLIGACION DE DAR SUMA DE DINERO INICIADAS POR AFPS',
'OBLIGACION DE HACER',
'OBLIGACION DE NO HACER',
'OFRECIMIENTO DE PAGO',
'OFRECIMIENTO DE PAGO DE BENEFICIOS ECONOMICOS',
'OFRECIMIENTO DE PAGO Y CONSIGNACION',
'OPOSICION',
'OPOSICION A ACUERDO DE EXCLUSION DE SOCIEDAD EN SOCIEDAD COMERCIAL DE RESPONSABILIDAD LIMITADA',
'OPOSICION A INSC. REC.',
'OPOSICION A LA INSCRIPCION DEL DERECHO DE POSICION',
'OPOSICION A PRORROGA DE SOCIEDAD COLECTIVA',
'OPOSICION A REDUCCION DE CAPITAL',
'OPOSICION AL MATRIMONIO',
'OPOSICION DE ACREEDOR DE HERENCIA',
'OPOSICION DE ACUERDO DE EXCLUSION DE SOCIO',
'OPOSICION DE VIAJE MENOR',
'OPSICION A ACUERDO DE EXCLUSION EN SOCIEDAD COLECTIVA',
'OTORGAMIENTO DE ESCRITURA PUBLICA',
'OTORGAMIENTO DE PENSION',
'OTORGAMIENTO DE TITULO',
'OTORGAMIENTO DE TRANSFERENCIA DE ACCIONES',
'OTORGAMIENTO VEHICULAR',
'OTROS PROCESOS QUE POR COMPETENCIA, MATERIA Y MONTO SE TRAMI',
'PAGO',
'PAGO DE AHORROS',
'PAGO DE APORTES PREVISIONALES',
'PAGO DE BENEFICIOS ECONOMICOS',
'PAGO DE BENEFICIOS SOCIALES Y/O INDEMNIZACION U OTROS BENEFICIOS ECONOMICOS',
'PAGO DE BONOS DE LA DEUDA AGRARIA',
'PAGO DE CREDITOS LABORALES (MAYORES DE 10 URP)',
'PAGO DE DEVENGADOS',
'PAGO DE DOLARES AMERICANOS',
'PAGO DE FRUTOS',
'PAGO DE HONORARIOS',
'PAGO DE INTERESES',
'PAGO DE MEJORAS',
'PAGO DE NUEVOS SOLES',
'PAGO DE PENSION DE JUBILACION',
'PAGO DE RATIOS SALARIALES (MAYORES DE 10 URP)',
'PAGO DE REMUNERACIONES',
'PAGO DE RETRIBUCION',
'PAGO DE SOLES Y DOLARES',
'PAGO DE SUMA RETND. INDBDM.DE CTS E INTERES.DE REMS.PEND.D.P',
'PAGO DE UTILIDADES',
'PAGO DE VACACIONES NO GOZADAS',
'PAGO EXTRAORDINARIO DE JUBILACION',
'PAGO INDEBIDO',
'PANDILLAJE PERNICIOSO',
'PARTICION CONVENCIONAL',
'PARTICION DE BIENES',
'PARTICION DE HERENCIA',
'PARTICIPACION EN UTILIDADES',
'PATRIA POTESTAD',
'PATRIMONIO FAMILIAR',
'PENAL (INFRACTORES) - PROC. DE INV. Y JUZ. CN Y A',
'PERDIDA DE SOCIEDAD DE GANANCIALES',
'PERDIDA O EXTINCION DE LA PATRIA POTESTAD',
'PERFECCIONAMIENTO DE CONTRATO',
'PERFECCIONAMIENTO DE ESCRITURA PUBLICA',
'PETICION Y EXCLUSION DE HERENCIA',
'PETICION Y/O EXCLUSION DE HERENCIA',
'PETITORIO MAYOR A 20 URP HASTA 50 URP',
'PETITORIO MAYOR A 20 URP Y MENOR DE 300 URP',
'PETITORIO MAYOR A 300 URP',
'PETITORIO NO SEA MAYOR A 20 URP',
'POR DEFINIR',
'POSESION DE ARMA DE FUEGO',
'POSESION DE LOS BIENES DE AUSENTE',
'PRESCRIPCION ADQUISITIVA',
'PRESTACION DE SERVICIOS',
'PRIVACION DE LA PATRIA POTESTAD',
'PROCESO UNICO',
'PRORRATEO DE ALIMENTOS',
'PROTECCION DE INTERESES DIFUSOS E INDIVIDUALES NIÑO Y ADOLECENTE',
'PROTOCOLIZACION',
'PRUEBA ANTICIPADA',
'QUEJA DE DERECHO',
'QUIEBRA',
'QUIEBRA JUDICIAL',
'REAJUSTE DE PENSION',
'RECISION DE CONTRATO',
'RECONOCIMIENTO DE BENEFICIOS SOCIALES DE EMPLEADAS DOMESTICAS',
'RECONOCIMIENTO DE BIEN PROPIO',
'RECONOCIMIENTO DE BIEN SOCIAL',
'RECONOCIMIENTO DE CONDICION DE SOCIO',
'RECONOCIMIENTO DE DEUDA',
'RECONOCIMIENTO DE DOCUMNETO',
'RECONOCIMIENTO DE EMBARAZO',
'RECONOCIMIENTO DE EXISTENCIA',
'RECONOCIMIENTO DE HECHO',
'RECONOCIMIENTO DE INVERSIONES',
'RECONOCIMIENTO DE LAUDOS ARBITRALES EXTRANJEROS',
'RECONOCIMIENTO DE LOS DERECHOS COMPRENDIDOS EN EL REGIMEN DE',
'RECONOCIMIENTO DE PATERNIDAD',
'RECONOCIMIENTO DE PROPIEDAD',
'RECONOCIMIENTO DE RESOLUCIONES JUDICIALES DICTADAS EN EL EXTRANJERO',
'RECONOCIMIENTO DE UNION DE HECHO',
'RECONOCIMIENTO O RESTABLECIMIENTO DEL DERECHO',
'RECONOCIMIENTO Y EJECUCION DE LAUDO ARBITRAL',
'RECTIFICACION DE AREA Y LINDEROS',
'RECTIFICACION DE ASIENTO DE INSCRIPCION',
'RECTIFICACION DE CONTRATO',
'RECTIFICACION DE DNI',
'RECTIFICACION DE PARTIDA',
'RECTIFICACION DE SENTENCIA',
'RECTIFICACION DE TITULO DE PROPIEDAD',
'RECTIFICACION EN LOS REGISTROS PUBLICOS',
'RECUSACION',
'REDUCCION DE ALIMENTOS',
'REDUCCION DE HIPOTECA',
'REEMBOLSO DE ACCIONES',
'REGIMEN DE VISITAS',
'REGISTRO DE PODER',
'REINTEGRO DE BENEFICIOS ECONOMICOS (MAYORES DE 10 URP)',
'REINTEGRO DE BENEFICIOS SOCIALES',
'REINTEGRO DE CTS',
'REINTEGRO DE PENSION DE JUBILACION',
'REINTEGRO DE PENSIONES INCREMENTADAS Y DEVENGADAS',
'REINTEGRO DE REM. INSOLUTAS',
'REINTEGRO DE REMUNERAC. POR CONCEPTO DE CLAUSULA DE GARANTIA',
'REINTEGRO DE REMUNERACIONES',
'REINTEGRO DE UTILIDADES',
'REIVINDICACION',
'RELATIVAS A MATERIA PREVISIONAL CONTENIDO ESENCIAL DEL DERECHO A LA PENSION',
'REMOCION DE ADMINISTRACION JUDICIAL',
'REMOCION DE ALBACEA',
'REMOCION DE CURADOR',
'REMOCION DE TUTORIA',
'RENDICION DE CUENTAS',
'RENTA VITALICIA',
'REPOSICION',
'RESCISION DE CONTRATO',
'RESOLUCION DE CONTRATO',
'RESOLUCION DE CONTRATO MERCANTIL',
'RESOLUCION DE PROMESA DE COMPRA VENTA',
'RESOLUCION Y RESCISION DE CONTRATO',
'RESPONSABILIDAD CIVIL DE LOS JUECES',
'RESPONSABILIDAD CIVIL EXTRACONTRACTUAL',
'RESPONSABILIDAD CIVIL POR ACCIDENTE DE TRANSITO',
'RESPONSABILIDAD EN LAS SOCIEDADES IRREGULARES',
'RESPONSABILIDAD SOCIAL FRENTE A ACREEDORES IMPAGOS',
'RESTABLECIMIENTO DE LA VERDADERA IDENTIDAD',
'RESTABLECIMIENTO O RECONOCIMIENTO DE DERECHOS',
'RESTITUCION DE ACCIONISTAS',
'RESTITUCION DE BIEN INMUEBLE',
'RESTITUCION DE BIEN PROPIO',
'RESTITUCION DE BONIFICACION MENSUAL POR SUPERV. Y OTROS',
'RESTITUCION DE INMUEBLE VENCIM. DE CONTRATO DE ARRENDAMIENTO',
'RESTITUCION DE LA PATRIA POTESTAD',
'RESTITUCION DE MENORES',
'RESTITUCION DE PATRIMONIO',
'RESTITUCION DE SERVIDUMBRE',
'RESTITUCION Y PAGO DE DINERO',
'RETENCION DE BIEN',
'RETIRO DE POSTE',
'RETRACTO',
'REVERSION DE EXPROPIACION',
'REVISION DE PROCEDIMIENTO DE EJECUCION / COBRANZA COACTIVA',
'REVISION JUDICIAL',
'REVISORIO',
'REVOCACION DE TESTAMENTO',
'SANEAMIENTO DE INMUEBLES',
'SANEAMIENTO POR EVICCION',
'SEGURIDAD DE HERENCIA',
'SEGURO DE VIDA',
'SEPARACION CONVENCIONAL Y/O DIVORCIO ULTERIOR',
'SEPARACION DE BIENES',
'SEPARACION DE PATRIMONIO',
'SERVIDUMBRE',
'SOLICITUD DE COPIA CERTIFICADA DE JUNTA O ASAMBLEA GENERAL DE SOCIOS',
'SOLICITUD DE INSCRIPCION DE ACUERDOS',
'SOLICITUDES POR DECISION DEL JUEZ CARENTES DE CONTENCION',
'SUCESION INTESTADA',
'SUMARISIMO',
'SUPRESION DE NOMBRE Y APELLIDO',
'SUSPENCION DE PATERNIDAD',
'SUSPENSION DE PATRIA POTESTAD',
'SUSTITUCION DEL REGIMEN DE PATRIMONIO O SEPARACION DE PATRIMONIO',
'TENENCIA',
'TENENCIA ILEGAL DE ARMA',
'TERCERIA',
'TERMINO DE FUNCIONES DEL LIQUIDADOR',
'TITULO SUPLETORIO',
'TRABAJADORAS DEL HOGAR',
'TRAFICO ILICITO DE DROGAS',
'TRANSACCION EXTRAJUDICIAL',
'TRANSMISION DE ACCIONES',
'TRANSMISION DE PARTICIPACIONES',
'TRANSMISION DE TITULOS VALORES DISTINTOS AL ENDOSO',
'TUTELA',
'UNION DE HECHO',
'UTILIDADES',
'VACACIONES NO GOZADAS Y TRUNCAS Y OTROS',
'VARIACION DE REGIMEN DE VISITAS',
'VARIACION DE TENENCIA',
'VARIACION EN LA FORMA DE PRESTAR ALIMENTOS',
'VENTA JUDICIAL DE BIENES PRENDADOS',
'VIOLACION DE NORMAS LEGALES',
'VIOLACION DEL DERECHO CONSTITUCIONAL',
'VIOLENCIA FAMILIAR',
'SEPARACION DE CUERPOS POR CAUSAL',
'SEPARACION DE CUERPOS POR MUTUO DISCENSO',
'NULIDAD DE ACUERDO DE ASAMBLEA GENERAL DE SOCIOS',
'HOMOLOGACION DE CONCILIACIONES PRIVADAS',
'INTERDICTO DE RECOBRAR',
'INTERDICTO DE ADQUIRIR',
'INTERDICTO DE CONSERVAR',
'OBLIGACION POR UN TERCERO',
'EJECUCION DE SUMA LIQUIDA',
'EJECUCION DE SUMA ILIQUIDA',
'IMPUGNACION DE LAUDO ARBITRAL',
'CUMPLIMIENTO DE DISPOSICION LEGAL',
'DERECHO DE REPETICION',
'OBLIGACION DE PAGO DE HONORARIOS PROFESIONALES',
'REVISIÓN DE BENEFICIOS SOCIALES LEY 27803',
'PAGO DE JUSTIPRECIO',
'INVALIDEZ DE DISPOSICIONES TESTAMENTARIAS',
'RESTITUCIÓN DE BIEN MATERIA DE ARRENDAMIENTO FINANCIERO',
'DISOLUCION Y LIQUIDACION JUDICIAL DE COOPERATIVA',
'PRESCRIPCIÓN EXTINTIVA DE DEUDA',
'OBLIGACIONES DE DAR HASTA 50 URP',
'TITULOS EJECUTIVOS HASTA 50 URP',
'CONSIGNACION DE DINERO',
'VULNERACION DE LA LIBERTAD SINDICAL',
'PRET. RELATIVA A MATERIA PREVISIONAL REFERIDA A CONTENIDO ESENCIAL DEL DERECHO A LA PENSION',
'CUMP.DE LA ADM. POR ACTUACION OBLIGADA POR MANDATO DE LEY O POR ACTO ADM',
'CESE POR ACTUACION MATERIAL NO SUSTENTADA EN ACTO ADMINISTRATIVO',
'INCAUTACION DE GARANTÍA MOBILIARIA LEY 28677',
'DESNATURALIZACIÓN DE CONTRATO',
'MEDIDA CAUTELAR DE EMBARGO CON CARÁCTER DE SECUESTRO CONSERVATIVO',
'MEDIDA CAUTELAR DE EMBARGO DE BIEN EN COPROPIEDAD',
'MEDIDA CAUTELAR DE EMBARGO DE BIEN EN REGISTRO DE COPROPIEDAD',
'MEDIDA CAUTELAR DE EMBARGO DE BIEN NO INSCRITO',
'MEDIDA CAUTELAR DE EMBARGO DE INMUEBLE NO INSCRITO',
'MEDIDA CAUTELAR DE EMBARGO DE SECUESTRO CON DESPOSESION Y ENTREGA',
'MEDIDA CAUTELAR DE EMBARGO EN FORMA DE INTERVENCION E INFORMACION',
'MEDIDA CAUTELAR DE EMBARGO EN FORMA DE INTERVENCION E RECAUDACION',
'SECUESTRO CONSERVATIVO SOBRE BIENES INFORMATICOS',
'SECUESTRO DE BIENES DENTRO DE UNA UNIDAD DE PRODUCCION',
'SECUESTRO DE DINERO, JOYAS u OTROS BIENES SIMILARES',
'SECUESTRO DE TITULOS DE CREDITOS',
'SECUESTRO DE VEHICULOS',
'INDEMNIZACIÓN POR INCUMPLIMIENTO DE ESPONSALES',
'VIOLENCIA CONTRA LAS MUJERES Y LOS INTEGRANTES DEL GRUPO FAMILIAR',
'DECLARACIÓN JUDICIAL DE DESPROTECCIÓN FAMILIAR',
'DETERMINACIÓN DE APOYOS Y SALVAGUARDAS',
'RECONOCIMIENTO DE APOYOS Y SALVAGUARDIAS',
'DESIGNACIÓN JUDICIAL DE APOYOS Y SALVAGUARDIAS',
'RESTITUCION DE CAPACIDAD JURIDICA',
'EXTINCION DE DOMINIO',
'DECLARACIÓN DE NULIDAD DE ACTOS ADMINISTRATIVOS',
'RELATIVAS A MATERIA PREVISIONAL',
'CONTENIDO ESENCIAL DEL DERECHO A LA PENSIÓN',
'CUMPLIMIENTO DE ACTUACIONES DISPUESTA POR ACTO ADMINISTRATIVO FIRME',
'CUMPLIMIENTO DE ACTUACIONES DISPUESTA POR LEY',
'RESTABLECIMIENTO DEL DERECHO TUTELADO',
'RECONOCIMIENTO DEL DERECHO TUTELADO',
'DECLARACIÓN DE INEFICACIA DE ACTOS ADMINISTRATIVOS'


];
datalistDistJudiciales:string[]=[
  '2° SALA LABORAL',
'SALA PENAL DE APELACIONES TRANSITORIA - SEDE CENTRAL',
'SALA PENAL LIQUIDADORA (ADICION FUNCIONES SALA PENAL)',
'JUZGADO INVESTIGACION PREP. MATERIA AMBIENTAL - SEDE CENTRAL',
'JUZG. DE INVESTIGACIÓN PREPARATORIA TRANSITORIO-AMBIENTAL',
'1º JUZGADO PENAL UNIPERSONAL TRANSITORIO',
'JUZGADO PENAL COLEGIADO SUPRAPROVINCIAL A - SEDE CENTRAL',
'5°JUZGADO CIVIL-SEDE CENTRAL',
'4° JUZGADO.DE TRABAJO DEL CUSCO',
'JUZGADO CIVIL TRANSITORIO-CUSCO',
'2º JUZGADO PENAL UNIPERSONAL TRANSITORIO - SEDE CENTRAL',
'2º JUZGADO COLEGIADO - SEDE CENTRAL',
'JUZG INV. PREP. DELITOS AMBIENTALES - SEDE CENTRAL',
'2°JUZG PENAL UNIP DELITOS AMBIENTALES - SEDE CENTRAL',
'JUZGADO PENAL COLEGIADO DELITOS AMBIENTALES - SEDE CENTRAL',
'SALA PENAL APELAC. DELITOS AMBIENTALES - SEDE CENTRAL',
'SALA PENAL LIQUIDADORA TRANSITORIA - SEDE CENTRAL',
'JUZGADO PENAL COLEGIADO (AD. SALA PENAL LIQ. T.)- SEDE CENTR',
'4° JUZGADO DE FAMILIA - SEDE CUSCO',
'7° JUZGADO INV. PREPARATORIA - SEDE CUSCO',
'3° JUZGADO PENAL UNIPERSONAL-SEDE CUSCO',
'3° JUZGADO PENAL UNIPERSONAL - SEDE CUSCO',
'4° JUZGADO PENAL UNIPERSONAL - SEDE CENTRAL',
'1º JUZG. INVEST. PREP. - DEL CORRUP FUNC - SEDE CENTRAL',
'4º JUZG. PENAL UNIPERSONAL - DEL CORRUPC FUNC - SEDE CENTRAL',
'2º SALA PENAL DE APELACIONES - CORRUP. FUNC. - SEDE CENTRAL',
'JUZGADO PENAL COLEG. SUPRAP. - CORRUP. FUNC. - SEDE CENTRAL',
'5º JUZGADO PENAL UNIPERSONAL - SEDE CENTRAL',
'5º JUZGADO DE TRABAJO DEL CUSCO',
'JUZGADO PENAL COLEGIADO SUPRAPROVINCIAL - SEDE CENTRAL',
'JUZGADO PENAL COLEGIADO SUPRAPROVINCIAL - SEDE CENTRAL',
'1° SALA PENAL DE APELACION (AD.FUNC.LIQUIDADOR) - SEDE',
'2° SALA PENAL DE APELACION (AD.FUNC.LIQUIDADOR) - SEDE',
'1°JUZGADO PENAL UNIPERSONAL-PROC. COMUN',
'1° JUZGADO DE PAZ LETRADO - FALTAS SS - SEDE WANCHAQ',
'2° JUZGADO DE PAZ LETRADO - FALTAS SS - SEDE WANCHAQ',
'8° JUZG. INVEST. PREPARAT. ESP. DELITOS CORRUP. FUNCIONARIOS',
'5°JUZG PENAL UNIP DELITOS AMBIENTALES - SEDE CENTRAL',
'JUZ. PENAL UNIPERSONAL - ITINERANTE A CUSCO (ANTA)',
'JUZ. PENAL UNIPERSONAL - ITINERANTE A CUSCO (CALCA)',
'5° JUZGADO DE FAMILIA - SUBESP VIOL CONTRA MUJER E INTGR GF',
'6° JUZGADO DE FAMILIA - SUBESP VIOL CONTRA MUJER E INTGR GF',
'7° JUZGADO DE FAMILIA - SUBESP VIOL CONTRA MUJER E INTGR GF',
'8° JUZGADO DE FAMILIA - SUBESP VIOL CONTRA MUJER E INTGR GF',
'9° JUZGADO DE FAMILIA - SUBESP VIOL CONTRA MUJER E INTGR GF',
'10° JUZGADO DE FAMILIA - SUBESP VIO CONTRA MUJER E INTGR GF',
'11° JUZGADO DE FAMILIA - SUBESP VIO CONTRA MUJER E INTGR GF',
'JUZGADO TRANSITORIO ESPEC. EXTINCIÓN DE DOMINIO-SEDE WANCHAQ',
'JUZGADO PENAL UNIPERSONAL (PROCESOS COMUNES)',
'JUZGADO PENAL LIQUIDADOR (AD. FUNC. EXT. DOM.)-SEDE WANCHAQ',
'6° JUZGADO DE TRABAJO DEL CUSCO',
'6° JUZGADO CIVIL - SEDE CENTRAL',
'JUZGADO CIVIL - SEDE WANCHAQ',
'JUZGADO PENAL UNIPERSONAL ITINERANTE A CUSCO (CHUMBIVILCAS)',
'1° SALA PENAL ',
'2° SALA PENAL ',
'3° SALA PENAL ',
'1° SALA PENAL LIQUIDADORA - Sede Central',
'SALA PENAL LIQUIDADORA PERMANENTE - Sede Central',
'1° SALA PENAL LIQUIDADORA TRANS - Sede Central',
'1° SALA DE APELACIONES - SEDE CENTRAL',
'SALA CONSTITUCIONAL Y SOCIAL',
'2° SALA PENAL DE APELACIONES - Sede Central',
'JUZGADO INV. PREPARATORIA (CORRUPCIÓN FUNC.)',
'1° JUZGADO PENAL UNIPERSONAL TRANSITORIO - SEDE CENTRAL',
'4° JUZGADO PENAL UNIPERSONAL SUPR.CORRUPCIÓN DE FUNCIONARIOS',
'4° JUZGADO PENAL UNIPERSONAL SUPR. CORR. FUNC.- COMÚN E INM.',
'1° JUZGADO CIVIL - Sede Central',
'2° JUZGADO CIVIL - Sede Central',
'3° JUZGADO CIVIL - Sede Central',
'4° JUZGADO CIVIL - Sede Central',
'5° JUZGADO CIVIL',
'CONTENCIOSO ADMINISTRATIVO - Sede Central',
'JUZGADO CIVIL TRANSITORIO',
'CONTENCIOSO ADMINISTRATIVO TRANSITORIO - S. Mesón',
'1° JUZGADO CIVIL - Sede Wanchaq',
'2° JUZGADO CIVIL - Sede Wanchaq',
'1°JUZ. DE PAZ LETRADO DE CUSCO-S.ExMeson Urb.La Florida C-14',
'2° JUZGADO DE PAZ LETRADO - S. Convertido',
'3°JUZ. DE PAZ LETRADO DE CUSCO-S.ExMeson Urb.La Florida C-14',
'2°JUZ. DE PAZ LETRADO DE CUSCO-Ex4°ExMeson-Urb.LaFloridaC-14',
'5° JUZGADO DE PAZ LETRADO - S. Mesón de Estrella',
'4° JUZGADO DE PAZ LETRADO - SEDE CALLE SAPHY',
'1° JUZGADO DE PAZ LETRADO - Sede Wanchaq',
'2° JUZGADO DE PAZ LETRADO - Sede Wanchaq',
'1° JUZGADO DE PAZ LETRADO - Sede Antonio L.',
'6° JUZGADO DE PAZ LETRADO - Sede Calle Saphy B',
'1°JUZ.DE PAZ LETRADO EN MATERIA LABORAL DEL CUSCO',
'2°JUZ.DE PAZ LETRADO EN MATERIA LABORAL DEL CUSCO',
'1° JUZGADO DE TRABAJO DEL CUSCO (Ley Antigua)',
'2° JUZGADO DE TRABAJO DEL CUSCO',
'3° JUZGADO.DE TRABAJO DEL CUSCO',
'1° JUZGADO DE TRABAJO DEL CUSCO',
'2do JUZGADO DE TRABAJO TRANSITORIO DEL CUSCO',
'1° JUZGADO FAMILIA DE CUSCO - S.ExMeson Urb. La Florida C-14',
'2° JUZGADO FAMILIA DE CUSCO - S.ExMeson Urb. La Florida C-14',
'3° JUZGADO FAMILIA DE CUSCO - S.ExMeson Urb. La Florida C-14',
'JUGADO DE FAMILIA TRANSITORIO S. Mesón de Est',
'2DO JUZGADO DE FAMILIA TRANSITORIO',
'SALA CIVIL(EX 1°) - SEDE CENTRAL',
'2° SALA CIVIL - Sede Central',
'1° SALA MIXTA ITINERANTE',
'1° JUZGADO PENAL',
'2° JUZGADO PENAL',
'3° JUZGADO PENAL',
'4° JUZGADO PENAL ',
'5° JUZGADO PENAL',
'6° JUZGADO PENAL',
'JUZGADO PENAL TRANSITORIO',
'JUZGADO PENAL LIQUIDADOR TRANSITORIO(1°)- Sede Central',
'JUZGADO PENAL LIQUIDADOR TRANSITORIO(2°)- Sede Central',
'JUZGADO PENAL LIQUIDADOR TRANSITORIO(3°)- Sede Central',
'1° JUZGADO PENAL TRASITORIO - Sede Antonio L.',
'JUZGADO DE TRABAJO TRANSITORIO DEL CUSCO',
'JUZGADO PENAL DE WANCHAQ',
'1° JUZGADO MIXTO',
'1° JUZGADO MIXTO - Sede Wanchaq',
'2° JUZGADO MIXTO - Sede Wanchaq',
'JUZGADO MIXTO TRANSITORIO - Sede Wanchaq',
'JUZGADO MIXTO DESCARGA TRANSITORIO',
'JUZGADO COLEGIADO',
'1° JUZ. DE INVES. PREPARATORIA - Sede Central',
'2° JUZ. INVES. PREP. - SEDE CENTRAL',
'3° JUZ. DE INVES. PREPARATORIA - Sede Central',
'4° JUZ. DE INVES. PREPARATORIA - Sede Central',
'5° JUZ. DE INVES. PREPARATORIA - Sede Central',
'6° JUZ. DE INVES. PREPARATORIA - Sede Central',
'1° SALA LABORAL - SEDE CENTRAL',
'1° JUZG. UNIPERSONAL - SEDE CENTRAL',
'2° JUZ. PENAL UNIPERSONAL - Sede Central',
'3° JUZ. PENAL UNIPERSONAL - Sede Central',
'4° JUZ. PENAL UNIPERSONAL - Sede Central',
'JUZGADO PENAL LIQUIDADOR - SEDE ACOMAYO',
'1° JUZGADO DE PAZ LETRADO - Sede Pomacanchi',
'JUZG. INV. PREP. (AD. FUNC. J. MIXTO) - SEDE ACOMAYO',
'1° JUZGADO DE PAZ LETRADO - Sede Acomayo',
'1° JUZGADO MIXTO - Sede Acomayo',
'JUZGADO MIXTO TRANSITORIO- Sede Acomayo',
'1° JUZGADO COLEGIADO - Sede Acomayo',
'1° JUZ. DE INVES. PREPARATORIA - Sede Acomayo',
'1° JUZGADO UNIPERSONAL - Sede Acomayo',
'JUZGADO PENAL LIQUIDDOR - SEDE ANTA',
'JUZGADO CIVIL - SEDE ANTA',
'JUZG. PENAL LIQUIDADOR (AD. FUNC. JIP) - SEDE ANTA',
'1° JUZGADO DE PAZ LETRADO - Sede Anta',
'1° JUZGADO MIXTO - Sede Anta',
'JUZGADO MIXTO TRANSITORIO - Sede Anta',
'1° JUZGADO COLEGIADO - Sede Anta',
'1° JUZ. DE INVES. PREPARATORIA - Sede Anta',
'1° JUZGADO UNIPERSONAL - Sede Anta',
'JUZGADO DE PAZ LETRADO - CALCA',
'JUZGADO PENAL LIQUIDADOR DE CALCA',
'1° JUZGADO MIXTO - Sede Calca',
'1° JUZGADO COLEGIADO - Sede Calca',
'1° JUZ. DE INVES. PREPARATORIA - Sede Calca',
'JUZGADO UNIPERSONAL DE CALCA',
'JUZGADO PENAL LIQUIDADOR - SEDE CANAS YANAOCA',
'JUZGADO PENAL UNIPERSONAL - ITINERANTE A CANAS',
'JUZGADO PENAL COLEGIADO - ITINERANTE A CANAS',
'1° JUZGADO DE PAZ LETRADO - SEDE CANAS YANAOCA',
'1° JUZGADO MIXTO - SEDE CANAS YANAOCA',
'1° JUZGADO COLEGIADO - Sede Canas Yanacoa',
'1° JUZ. DE INVES. PREPARATORIA - SEDE CANAS YANAOCA',
'JUZGADO UNIPERSONAL DE CANAS',
'JUZGADO PENAL LIQUIDADOR - SEDE SICUANI',
'JUZGADO PENAL LIQUIDADOR - SEDE SICUANI',
'1° SALA MIXTA (EN ADIC. SALA PENAL LIQUIDADORA)',
'1° JUZGADO CIVIL - SEDE SICUANI',
'2° JUZGADO CIVIL - SEDE SICUANI',
'JUZGADO PENAL LIQUIDADOR (AD. FUNC. 2° J.CIVIL)-SEDE SICUANI',
'1° SALA PENAL DE APELACIONES - Sede Sicuani',
'2° JUZG. INVEST. PREPARAT. VIOL.C.MUJER E IGF-SEDE SICUANI',
'JUZGADO DE PAZ LETRADO CAMANTI - ITINERA A SICUANI',
'1° JUZGADO DE PAZ LETRADO - Sede Sicuani',
'2° JUZGADO DE PAZ LETRADO - Sede Sicuani',
'JUZGADO DE PAZ LETRADO - Sede Tinta_',
'1° JUZGADO PENAL LIQUID. TRANS. - Sede Sicuani',
'1° JUZGADO MIXTO - Sede Sicuani',
'JUZGADO MIXTO - SEDE SICUANI',
'1° JUZGADO COLEGIADO - Sede Sicuani',
'1° JUZ. DE INVES. PREPARATORIA - Sede Sicuani',
'1° SALA MIXTA - Sede Sicuani',
'1° JUZGADO UNIPERSONAL - Sede Sicuani',
'JUZGADO DE LA INVESTIGACION PREPARATORIA - SEDE SANTO TOMAS',
'JUZGADO PENAL UNIPERSONAL TRANSITORIO - SEDE SANTO TOMÁS',
'JUZGADO COLEGIADO - SEDE SANTO TOMÁS',
'JUZGADO PENAL UNIPERSONAL - SEDE SANTO TOMÁS',
'JUZGADO PENAL UNIPERSONAL ITINERANTE A CCUSCO (CHUMBIVILCAS)',
'1° JUZGADO DE PAZ LETRADO - Sede Santo Tomás',
'JUZGADO DE PAZ LETRADO - Sede Livitaca',
'1° JUZGADO PENAL LIQUIDADOR - Sede Santo Tomás',
'1° JUZGADO MIXTO - Sede Santo Tomás',
'2° JUZGADO MIXTO - Sede Santo Tomás',
'1° JUZGADO COLEGIADO - Sede Santo Tomás',
'1° JUZ. DE INVES. PREPARATORIA - Sede Santo Tomás',
'1° JUZGADO UNIPERSONAL - Sede Santo Tomás',
'JUZGADO PENAL LIQUIDADOR - SEDE ESPINAR',
'JUZGADO CIVIL - SEDE ESPINAR',
'JUZG. PENAL LIQUIDADOR (AD. FUNC. JIP) - SEDE ESPINAR',
'1° JUZGADO DE PAZ LETRADO - Sede Espinar',
'1° JUZ. PENAL LIQUID. TRANS. - Sede Espinar',
'1° JUZGADO MIXTO - Sede Espinar',
'1° JUZGADO COLEGIADO - Sede Espinar Yauri',
'1° JUZ. DE INVES. PREPARATORIA - Sede Espinar',
'1° JUZ. UNIPERSONAL SUPRAPROVINCIAL - Sede Espinar',
'JUZGADO PENAL LIQUIDADOR - SEDE SANTA ANA',
'SALA MIXTA DESCENTRALIZADA -SANTA ANA',
'SALA MIXTA DES. EN ADIC. SALA PENAL DE APELACION- SANTA ANA',
'SALA PENAL LIQUIDADORA-SANTA ANA',
'JUZG. DE INVESTIGACIÓN PREPARATORIA TRANSITORIO-SANTA ANA',
'SALA MIXTA DESCENTRALIZADA DE LA CONVENCION',
'SALA APELACIONES DE LA CONVENCION',
'2° JUZG. FAMILIA SUB.VIOLENCIA C.MUJER E IGF- SEDE SANTA ANA',
'JUZGADO CIVIL - SEDE SANTA ANA',
'JUZGADO LIQUIDADOR (AD. FUNC. JUZG. CIVIL) - SEDE SANTA ANA',
'1° JUZGADO DE PAZ LETRADO - Sede Quillabamba',
'2° JUZGADO DE PAZ LETRADO - Sede Quillabamba',
'JUZGADO DE PAZ LETRADO - Sede Quellouno',
'JUZGADO DE PAZ LETRADO - Sede Sede Maranura',
'1° JUZ ESPECIALIZADO DE FAMILIA - Sede Quillabamba',
'1° JUZGADO PENAL LIQUIDADOR - Sede Quillabamba',
'JUZGADO MIXTO - Sede Quillabamba',
'1° JUZGADO MIXTO TRANSITORIO - Sede Quillabamba',
'1° JUZGADO COLEGIADO - Sede Quillabamba Quillabamba',
'1° JUZ. DE INVES. PREPARATORIA - Sede Quillabamba',
'JUZ. DE INVES. PREPARATORIA - Sede Maranura',
'1° JUZGADO UNIPERSONAL - Sede Quillabamba',
'JUZG. INV. PREP. (AD. FUNC. J. MIXTO) - SEDE PARURO',
'1° JUZGADO DE PAZ LETRADO - Sede Paruro',
'1° JUZGADO PENAL LIQUIDADOR - Sede Paruro',
'1° JUZGADO MIXTO - Sede Paruro',
'1° JUZGADO COLEGIADO - Sede Paruro ',
'1° JUZ. DE INVES. PREPARATORIA - Sede Paruro',
'1° JUZGADO UNIPERSONAL - Sede Paruro',
'JUZG. INV. PREP. (AD. FUNC. J. MIXTO) - SEDE PAUCARTAMBO',
'1° JUZGADO DE PAZ LETRADO - Sede Paucartambo',
'1° JUZGADO PENAL LIQUIDADOR - Sede Paucartambo',
'1° JUZGADO MIXTO - Sede Paucartambo',
'1° JUZGADO COLEGIADO - Sede Paucartambo',
'1° JUZ. DE INVES. PREPARATORIA - Sede Paucartambo',
'1° JUZGADO UNIPERSONAL - Sede Paucartambo',
'JUZGADO PENAL UNIPERSONAL - SEDE QUISPICANCHIS',
'JUZGADO PENAL LIQUIDADOR (AD. FUNCIONES JUP) - QUISPICANCHIS',
'JUZ. PENAL LIQUIDADOR - ITINERANTE CANAS',
'JUZ. PENAL UNIPERSONAL - ITINERANTE CANAS',
'JUZGADO PENAL COLEGIADO-SEDE QUISPICANCHI',
'JUZGADO PENAL COLEGIADO-ITINERANTE CANAS',
'JUZGADO DE PAZ LETRADO CAMANTI - ITINERA A URCOS',
'JUZGADO CIVIL - SEDE QUISPICANCHIS',
'2° JUZG. INVEST. PREPARAT. VIOL.C.MUJER E IGF-SEDE QUISPICAN',
'1° JUZGADO DE PAZ LETRADO - Sede Quispicanchis',
'JUZGADO DE PAZ LETRADO - Sede Ocongate',
'1° JUZGADO PENAL LIQUIDADOR - Sede Quispicanchis',
'1° JUZGADO DE PAZ LETRADO - Sede Camanti',
'1° JUZ. DE INVES. PREPARATORIA - Sede Camanti',
'1° JUZGADO MIXTO - Sede Quispicanchis',
'1° JUZGADO COLEGIADO - Sede Quispicanchis',
'1° JUZ. DE INVES. PREPARATORIA - Sede Quispicanchis',
'1° JUZGADO UNIPERSONAL - Sede Quispicanchis',
'JUZGADO MIXTO ITINERANTE-URUBAMBA',
'JUZGADO PENAL UNIPERSONAL ITINERANTE-URUBAMBA',
'JUZGADO CIVIL - SEDE URUBAMBA',
'1° SALA PENAL DE APELACIONES - Sede Urubamba',
'2° JUZG. PENAL UNIPERSONAL VIOL.C.MUJER E IGF-SEDE URUBAMBA',
'2° JUZG. INV. PREPARATORIA VIOL.C.MUJER E IGF-SEDE URUBAMBA',
'JUZGADO DE FAMILIA SUBESPEC.VIOL.C.MUJER E IGF-SEDE URUBAMBA',
'1° JUZGADO DE PAZ LETRADO - Sede Urubamba',
'1° JUZGADO DE PAZ LETRADO S. Urubamba - A.C.',
'JUZGADO PENAL LIQUIDADOR - S. Urubamba',
'1° JUZGADO MIXTO - Sede Urubamba',
'1° JUZGADO MXTO - S. Urubamba. - A.C.',
'JUZGADO MIXTO TRANSITORIO - Sede Urubamba',
'1° JUZGADO COLEGIADO SUPRAPROVINCIAL - S. Urubamba',
'1° JUZGADO COLEGIADO - S. Urubamba',
'1° JUZ. DE INVES. PREPARATORIA - S. Urubamba',
'1° JUZ. DE INVES. PREPARATORIA - S. Urubamba - A.C',
'1° SALA MIXTA DESC. DE URUBAMBA - S. Urubamba',
'1° JUZ. UNIPERSONAL  - S. Urubamba',
'1° JUZGADO UNIPERSONAL S. Urubamba. - A.C.',
'JUZGADO PENAL LIQUIDADOR - SEDE MACHUPICCHU',
'JUZG. INV. PREP. (AD. FUNC. J. MIXTO) - SEDE MACHU PICCHU',
'1° JUZGADO DE PAZ LETRADO - Sede Machupicchu',
'1° JUZGADO MIXTO - Sede Machupicchu',
'1° JUZGADO COLEGIADO - Sede Machupicchu',
'1° JUZ. DE INVES. PREPARATORIA - Sede Machupicchu',
'1° JUZGADO UNIPERSONAL - Sede Machupicchu',
'1°JUZGADO MIXTO DE SANTIAGO',
'1° JUZGADO PENAL LIQUIDADOR (AD. FUNC. 1° J MIXTO)- SANTIAGO',
'2° JUZGADO PENAL LIQUIDADOR (AD. FUNC. 2° J MIXTO)- SANTIAGO',
'2° JUZGADO DE PAZ LETRADO - SEDE SANTIAGO',
'JUZGADO CIVIL - SEDE SANTIAGO AV. M.B.',
'2° JUZGADO DE PAZ LETRADO - SEDE SANTIAGO AV. M.B.',
'1° JUZGADO DE PAZ LETRADO - Sede Santiago Av. M.B.',
'1° JUZGADO DE PAZ LETRADO - Sede Pisac',
'2° JUZGADO DE PAZ LETRADO - Sede Santiago Av. M.B.',
'JUZGADO DE PAZ LETRADO TRANSITORIO- Sede Santiago Av. M.B.',
'Juzgado Penal Liquidador - Sede Central',
'Juzgado Penal Transitoria - Sede Santiago',
'JUZGADO CIVIL - Sede Santiago Av. M.B.',
'2° JUZGADO MIXTO DE SANTIAGO',
'JUZGADO MIXTO TRANSITORIO - S. Mesón de Estrella',
'1 JUZGADO CIVIL TRANSITORIO - Sede Santiago',
'2 JUZGADO CIVIL TRANSITORIO - Sede Santiago',
'1° JUZGADO MIXTO TRANSITORIO - Sede Santiago',
'1° JUZ. DE INVES. PREPARATORIA - Sede Pisac',
'1° JUZGADO DE PAZ LETRADO - Sede Quebrada',
'1° JUZ. DE INVES. PREPARATORIA - Sede Quebrada',
'JUZGADO DE PAZ LETRADO',
'JUZGADO DE INVESTIGACIÓN PREPARATORIA',
'2° JUZG. PENAL UNIPERSONAL VIOL.C.MUJER E IGF-SEDE ECHARATE',
'JUZG. INV. PREP. (AD. FUNC. J. MIXTO) - SEDE ECHARATE',
'1° JUZGADO DE PAZ LETRADO - Sede de Echarate',
'1° JUZGADO MIXTO - Sede de Echarate',
'1° JUZGADO COLEGIADO - Sede Echarate',
'1° JUZ. DE INVES. PREPARATORIA - Sede de Echarate',
'1° JUZGADO UNIPERSONAL - Sede de Echarate',
'1° JUZGADO DE PAZ LETRADO - Sede Pisac',
'1° JUZ. DE INVES. PREPARATORIA - Sede Pisac',
'1° JUZGADO DE PAZ LETRADO - Sede San Jerónimo',
'2° JUZGADO DE PAZ LETRADO - SAN SEBASTIÁN',
'2° JUZGADO DE PAZ LETRADO - SAN SEBASTÍAN',
'1° JUZGADO DE PAZ LETRADO - San Sebastían',
'JUZGADO DE PAZ LETRADO-SEDE TINTA',
'JUZGADO DE PAZ LETRADO-SEDE OCONGATE',
'JUZGADO DE PAZ LETRADO-SEDE LIVITACA',
'JUZGADO DE PAZ LETRADO-SEDE QUELLOUNO',
'JUZGADO DE PAZ LETRADO-SEDE MARANURA',
'JUZGADO DE INVEST. PREPARATORIA-SEDE MARANURA',
'JUZGADO DE PAZ LETRADO CAMANTI - ITINERA A SICUANI',
'1° JUZGADO DE PAZ LETRADO - Sede Camanti',
'1° JUZ. DE INVES. PREPARATORIA - Sede Camanti',
'1° JUZGADO DE PAZ LETRADO - Sede Pomacanchi',
'1° JUZG. PENAL UNIPERSONAL VIOL.C.MUJER E IGF-SEDE MESON',
'2° JUZG. PENAL UNIPERSONAL VIOL.C.MUJER E IGF-SEDE MESON',
'3° JUZG. PENAL UNIPERSONAL VIOL.C.MUJER E IGF-SEDE MESON',
'4° JUZG. PENAL UNIPERSONAL VIOL.C.MUJER E IGF-SEDE MESON',
'JUZG. PENAL COLEGIADO CONFORMADO VIOL.C.MUJ.E IGF-SEDE MESON',
'1° JUZG. INVEST. PREPARATORIA VIOL.C.MUJER E IGF-SEDE MESON',
'2° JUZG. INVEST. PREPARATORIA VIOL.C.MUJER E IGF-SEDE MESON',
'3° JUZG. INVEST. PREPARATORIA VIOL.C.MUJER E IGF-SEDE MESON',
'SALA SUPREMA CIVIL',
'SALA SUPREMA CONSTITUCIONAL Y SOCIAL',
'SALA SUPREMA CIVIL PERMANENTE',
'SALA SUPREMA CIVIL TRANSITORIA',
'SALA DE DERECHO CONSTITUCIONAL Y SOCIAL PERMANENTE',
'PRIMERA SALA DE DERECHO CONSTITUCIONAL Y SOCIAL TRANSITORIA',
'SEGUNDA SALA DE DERECHO CONSTITUCIONAL Y SOCIAL TRANSITORIA',
'TERCERA SALA DE DERECHO CONSTITUCIONAL Y SOCIAL TRANSITORIA',
'()2° JUZGADO PENAL COLEGIADO CONFORMADO - SEDE MESON',
'2° JUZGADO PENAL COLEGIADO CONFORMADO - SEDE MESON',
'JUZGADO DE FAMILIA - SEDE ANTA',
'JUZGADO DE FAMILIA - SEDE SICUANI',
'JUZGADO DE FAMILIA - SEDE SANTO TOMÁS',
'JUZGADO DE FAMILIA - SEDE ESPINAR',
'JUZGADO DE PAZ LETRADO-SEDE VILCABAMBA',
'JUZG. DE INVEST. PREPAR. (AD. FUNC. JPL) - SEDE VILCABAMBA',
'JUZGADO DE PAZ LETRADO - SEDE VILCABAMBA',
'JUZG. DE INVEST. PREPAR. (AD. FUNC. JPL) - SEDE VILCABAMBA',
'SALA CIVIL TRANSITORIA - CUSCO',
'JUZGADO DE FAMILIA TRANSITORIO - CUSCO',
'2° JUZGADO PENAL UNIPERSONAL TRANSITORIO ESP. DCF - CUSCO',
'JUZG. PENAL UNIPERS. DESCAR. ESP. DELIT. CORRUP. FUNC.-CUSCO',
'2° JUZG. PENAL UNIPERSONAL VIOL.C.MUJER -SEDE QUILLABAMBA',
'1° J. PENAL COLEGIADO TRANS. VIOL.C.MUJ.E IGF-SEDE HUANCARO',
'2° J. PENAL COLEGIADO TRANS. VIOL.C.MUJ.E IGF-SEDE HUANCARO',
'JUZGADO CIVIL DE SANTIAGO ITINERA A URUBAMBA',
'JUZGADO DE PAZ LETRADO DE QUELLOUNO ITINERA A OCABAMBA',
'JUZGADO CIVIL DE SANTIAGO ITINERA A URUBAMBA - BAJA',
'JUZGADO CIVIL DE SANTIAGO ITINERA A URUBAMBA',
'JUZG. INVESTIGACIÓN PREPARATORIA TRANSITORIO - SEDE CENTRAL',
'2° JUZGADO PENAL UNIPERSONAL TRANSITORIO - SEDE CENTRAL'
]
index:number=0//indice de la lista demandante o demandado
index_indizacion:number=0//indice del la lista de indizacion
itemTemp:any=[]//item temporal
modificar_parte=false//condicional que permitira modificar parte
modificar_indizacion=false
disableButtonEliminar='display: none'
titulo_boton='Agregar'
estado_indizado_temp:boolean=false
id_indizacion:number=0

//[{"nombre":"ernesto","ap_paterno":"francisco","ap_materno":"arangure","dni":"45785623"},{"nombre":"francisco","ap_paterno":"arangure","ap_materno":"torres","dni":"19635784"}]
TempDemandante:any={
  nombre:'',
  ap_paterno:'',
  ap_materno:'',
  dni:'',
}
TempDemandado:any={
  nombre:'',
  ap_paterno:'',
  ap_materno:'',
  dni:'',

}



//datos del collapse para la tabla de vehiculos----------------------------------------



pdfUrl: SafeResourceUrl | null =null;
private myModal: any;
ngOnInit(): void {
  const params=this.activatedRoute.snapshot.params

    console.log(params['id_expediente'])

    this.expedienteService.obtenerExpedienteDetalle(params['id_expediente']).subscribe(
        res=>{
           this.detalleExpediente=res
            this.detalleExpediente=this.detalleExpediente
           console.log(this.detalleExpediente)
           if(this.detalleExpediente.estado_indizado==true){
            this.estado_indizado_temp=true
            this.RecuperarDatos(this.detalleExpediente.id_expediente,this.detalleExpediente.juzgado_origen,this.detalleExpediente.tipo_proceso,this.detalleExpediente.materia,this.detalleExpediente.fecha_inicial,this.detalleExpediente.fecha_final,this.detalleExpediente.demandante,this.detalleExpediente.demandado)
           }
           this.data_expediente.id_inventario= this.detalleExpediente.id_inventario
           this.data_expediente.id_responsable= this.datosCompartidosService.credentials.id_usuario
           this.data_expediente.nombre_expediente= this.detalleExpediente.nombre_expediente
           this.obtenerDocumentoDigitalizado(this.detalleExpediente.id_expediente)
        },
        err=>{
          console.error(err)
        }   
       )
       this.pdfUrl = this.sanitizer.bypassSecurityTrustResourceUrl(`assets/documentos/error/error_carga2.pdf`);
}
obtenerDocumentoDigitalizado(id_expediente:number){
  this.digitalizacionService.obtenerDocumentoXidExpediente(id_expediente).subscribe(
    res=>{
        let digitalizadoTemp:any=res
        console.log(digitalizadoTemp)
        this.mostrarDocumento(digitalizadoTemp.documento)
    },
    err=>{
        console.error(err)
    }
  )
}


limpiarCamposDemandante(){
  
  this.disableButtonEliminar='display: none';
   (<HTMLInputElement>document.getElementById('demandante')).value='';
   (<HTMLInputElement>document.getElementById('demandante_identificador')).value='';
   
}
limpiarCamposDemandado(){
  (<HTMLInputElement>document.getElementById('demandado')).value='';
  (<HTMLInputElement>document.getElementById('demandado_identificador')).value='';
  
}
limpiarCamposIndizacion(){
 
  (<HTMLInputElement>document.getElementById('indizacion_descripcion')).value='';
  (<HTMLInputElement>document.getElementById('indizacion_indice')).value='';
  (<HTMLInputElement>document.getElementById('indizacion_fojas')).value='';
  (<HTMLInputElement>document.getElementById('fecha_indice')).value='';
  (<HTMLInputElement>document.getElementById('indizacion_checkbox_original')).checked=false;
  (<HTMLInputElement>document.getElementById('indizacion_checkbox_copia')).checked=false;
  (<HTMLInputElement>document.getElementById('indizacion_checkbox_color')).checked=false;
  (<HTMLInputElement>document.getElementById('indizacion_checkbox_escalagris')).checked=false;
  (<HTMLInputElement>document.getElementById('indizacion_textarea')).value='';

  (<HTMLInputElement>document.getElementById('indizacion_descripcion_2')).value='';
  (<HTMLInputElement>document.getElementById('indizacion_indice_2')).value='';
  (<HTMLInputElement>document.getElementById('indizacion_fojas_2')).value='';
  (<HTMLInputElement>document.getElementById('fecha_indice_2')).value='';
  (<HTMLInputElement>document.getElementById('indizacion_checkbox_original_2')).checked=false;
  (<HTMLInputElement>document.getElementById('indizacion_checkbox_copia_2')).checked=false;
  (<HTMLInputElement>document.getElementById('indizacion_checkbox_color_2')).checked=false;
  (<HTMLInputElement>document.getElementById('indizacion_checkbox_escalagris_2')).checked=false;
  (<HTMLInputElement>document.getElementById('indizacion_textarea_2')).value='';
  this.modificar_indizacion=false
  
 
}

 enviarTablaDemandantes() {
   // Obtener datos del demandante
   let  datosDemandante:any={}
   datosDemandante.demandante = (<HTMLInputElement>document.getElementById('demandante')).value;
   datosDemandante.identificador = (<HTMLInputElement>document.getElementById('demandante_identificador')).value;
   this.listaTempDemanantes.push(datosDemandante);
   this.closeModal();
   this.limpiarCamposDemandante();
}
enviarTablaDemandados(){
  // Obtener datos del demandante
  let  datosDemandado:any={}
  datosDemandado.demandado = (<HTMLInputElement>document.getElementById('demandado')).value;
  datosDemandado.identificador = (<HTMLInputElement>document.getElementById('demandado_identificador')).value;
  this.listaTempDemandados.push(datosDemandado);
  this.closeModal();
  this.limpiarCamposDemandado();
}
// guardar(){
//   // this.ModificarExpediente()
//   // this.GuardarPartes()
//   // this.MensajeDeGuardado()
// }
ModificarIndizacion(){
 
  let body:any={}
  let jsonStringIndizacion = JSON.stringify(this.dataIndizacion);
  body.indizacion=jsonStringIndizacion
  body.observaciones=(<HTMLInputElement>document.getElementById('observaciones_generales')).value;

  this.indizacionService.modificarIndizacionIndice(body,this.id_indizacion).subscribe(
    res=>{
        console.log(res)
        this.ModificarDatosComplementariosExpediente()
        this.mensajeGuardado()
    },
    err=>{
        console.error(err)
    }
  )
}
RecuperarDatos(id_expediente:number,juzgado_origen: string, tipo_proceso: string, materia: string, fecha_inicio: string, fecha_final: string, demandantes:string,demandados:string) {
  (document.getElementById('input_juzgado_origen') as HTMLInputElement).value = juzgado_origen;
  (document.getElementById('select_tipo_proceso') as HTMLInputElement).value = tipo_proceso;
  (document.getElementById('input_materia') as HTMLInputElement).value = materia;

  // Extraer la parte de la fecha (YYYY-MM-DD) de la cadena ISO
  const fechaInicioStr = fecha_inicio.split('T')[0];
  const fechaFinalStr = fecha_final.split('T')[0];

  (document.getElementById('fecha_inicio') as HTMLInputElement).value = fechaInicioStr;
  (document.getElementById('fecha_final') as HTMLInputElement).value = fechaFinalStr;

  
  this.listaTempDemanantes = JSON.parse(demandantes);
  this.listaTempDemandados = JSON.parse(demandados);
  

  this.indizacionService.indizacionDetalleXidExpediente(id_expediente).subscribe(
    res=>{
        let datosIndizacion:any=res
        this.dataIndizacion= JSON.parse(datosIndizacion[0].indizacion)
        this.id_indizacion=datosIndizacion[0].id_indizacion;
        console.log(datosIndizacion[0]);
        (<HTMLInputElement>document.getElementById('observaciones_generales')).value= datosIndizacion[0].observaciones;
    },
    err=>{
        console.error(err)
    }
  )

}

//en este caso usaremos el modificar ya que el preparado es un agregado al expediente alistado por el supervisor
// ModificarExpediente(){
//   const params=this.activatedRoute.snapshot.params
//   const id_expediente=params['id_expediente']
//   this.expedienteService.modificarExpediente(this.data_expediente,id_expediente).subscribe(
//     res=>{
//       console.log(res)
//     },
//     err=>{
//       console.error(err)
//     }
//   )
// }


//MODAL PARA MANEJAR DEMANDANTE
  openModalDemandante() {
    this.limpiarCamposDemandante()
    this.myModal = new bootstrap.Modal(document.getElementById('Modal_Demandante'));
    this.modificar_parte=false
    this.titulo_boton='Agregar'
    this.disableButtonEliminar='display: none'
    this.myModal.show();
  }
  openModalDemandanteModificar() {
    this.myModal = new bootstrap.Modal(document.getElementById('Modal_Demandante')); 
    this.modificar_parte=true
    this.titulo_boton='Modificar'
    this.disableButtonEliminar='display: block'
    this.myModal.show();
  }

//MODAL PARA MANEJAR DEMANDANDO
  openModalDemandado() {
    this.limpiarCamposDemandado()
    this.myModal = new bootstrap.Modal(document.getElementById('Modal_Demandado'));
    this.modificar_parte=false
    this.titulo_boton='Agregar'
    this.disableButtonEliminar='display: none'
    this.myModal.show();
  }
  openModalDemandadoModificar() {
    this.myModal = new bootstrap.Modal(document.getElementById('Modal_Demandado'));
    this.modificar_parte=true
    this.titulo_boton='Modificar'
    this.disableButtonEliminar='display: block'
    this.myModal.show();
  }


  closeModal() {
    // Ocultar el modal utilizando la instancia almacenada
    this.myModal.hide();

    
  }
  

CrearIndizacion(){
  const params=this.activatedRoute.snapshot.params
  let body:any={}
  let jsonStringIndizacion = JSON.stringify(this.dataIndizacion);
  body.id_expediente=params['id_expediente']
  body.id_responsable=this.datosCompartidosService.credentials.id_usuario
  body.indizacion=jsonStringIndizacion
  body.observaciones=(<HTMLInputElement>document.getElementById('observaciones_generales')).value;

  this.indizacionService.crearIndizacion(body).subscribe(
    res=>{
        console.log(res)
        this.ModificarDatosComplementariosExpediente()
        this.ModificarEstadoIndizadoExpediente()
        this.mensajeGuardado()
    },
    err=>{
        console.error(err)
    }
  )

}


ModificarDatosComplementariosExpediente()//
{
  let body:any={}
  body.id_expediente=this.detalleExpediente.id_expediente;
  body.juzgado_origen=(<HTMLInputElement>document.getElementById('input_juzgado_origen')).value;
  body.materia=(<HTMLInputElement>document.getElementById('input_materia')).value;
  body.fecha_inicial=(<HTMLInputElement>document.getElementById('fecha_inicio')).value;
  body.fecha_final=(<HTMLInputElement>document.getElementById('fecha_final')).value;
  body.tipo_proceso=(<HTMLInputElement>document.getElementById('select_tipo_proceso')).value;
 
if (!body.juzgado_origen || !body.materia || !body.tipo_proceso || !body.fecha_inicial || !body.fecha_final ) {
alert('Por favor, complete los datos complementarios.');
} 

else if (this.listaTempDemanantes.length === 0 || this.listaTempDemandados.length === 0 ) {
alert('Las listas de demandantes, demandados y de indización no pueden estar vacías.');
} 
else {
console.log('Datos validados correctamente', body);
let jsonStringDemanantes = JSON.stringify(this.listaTempDemanantes);
let jsonStringDemandados = JSON.stringify(this.listaTempDemandados);
  body.demandante=jsonStringDemanantes
  body.demandado=jsonStringDemandados
  console.log(body)
  const params=this.activatedRoute.snapshot.params
this.expedienteService.modificarExpedienteEnIndizacion(body,params['id_expediente']).subscribe(
  res=>{
      console.log(res)
  },
  err=>{
      console.error(err)
  }
)

}
}

 ModificarEstadoIndizadoExpediente(){
    this.expedienteService.modificarEstadoIndizado({estado_indizado:true},this.detalleExpediente.id_expediente).subscribe(
      res=>{
           console.log(res)
      },
      err=>{
           console.error(err)
      }
    )
}

  volver(){
    this.router.navigate(['/principal/indizador/expedientes/',this.detalleExpediente.id_inventario])
  }

  mensajeGuardado(){
    Swal.fire({
      position: "top-end",
      icon: "success",
      title: "LA INDIZACION HA SIDO GUARDADO",
      showConfirmButton: false,
      timer: 1500
    });
    this.volver()
  }

  //#region ==========CONVERTIR DE BASE64 A PDF PARA MOSTRARSE EN EL VISUALIZADOR DE DEL NAVEGADOR===================== 
  // convertir de base64 a pdf
  // Paso 1: Decodificar el string Base64
  base64ToBytes(base64:string) {
    const binaryString = atob(base64);
    const length = binaryString.length;
    const bytes = new Uint8Array(length);
    
    for (let i = 0; i < length; i++) {
      bytes[i] = binaryString.charCodeAt(i);
    }
  
    return bytes;
  }
  
  // Paso 2: Crear un objeto Blob para un PDF
  base64ToPdfBlob(base64:string) {
    const bytes = this.base64ToBytes(base64);
    return new Blob([bytes], { type: "application/pdf" });
  }
  
  // Ejemplo de uso
  //para hacegurar un correcto respaldo del documento realizamos una previsualizacion del archivo en base64 que guardaremos en la base de datos
   mostrarDocumento(documento:string){ 
    const pdfBlob = this.base64ToPdfBlob(documento);
    console.log(pdfBlob)
   this.pdfUrl = this.sanitizer.bypassSecurityTrustResourceUrl(URL.createObjectURL(pdfBlob));
  
   }
  //#endregion ====================================================================================================

//MANEJADOR DE DATOS DEMANDANTE
  mostrarDatosDemandante(index:number){
    this.index=index
    this.openModalDemandanteModificar();
    (<HTMLInputElement>document.getElementById('demandante')).value=this.listaTempDemanantes[index].demandante;
     (<HTMLInputElement>document.getElementById('demandante_identificador')).value=this.listaTempDemanantes[index].identificador;
  }
  modificarDatosDemandante(){
       // Obtener datos del demandante
  let  datosDemandante:any={}
  datosDemandante.demandante = (<HTMLInputElement>document.getElementById('demandante')).value;
  datosDemandante.identificador = (<HTMLInputElement>document.getElementById('demandante_identificador')).value;
  // Agregar los datos a la lista temporal
  this.listaTempDemanantes[this.index]=datosDemandante;
  // Cerrar el modal
  this.closeModal();

  
  }
  eliminarDatosDemandante(){
    this.listaTempDemanantes.splice(this.index, 1);
    this.closeModal()
  }


  //MANEJADOR DE DATOS DEMANADO 
  mostrarDatosDemandado(index:number){
    this.index=index
    this.openModalDemandadoModificar();
    (<HTMLInputElement>document.getElementById('demandado')).value=this.listaTempDemandados[index].demandado;
     (<HTMLInputElement>document.getElementById('demandado_identificador')).value=this.listaTempDemandados[index].identificador;
  }
  modificarDatosDemandado(){
       // Obtener datos del demandante
  let  datosDemandado:any={}
  datosDemandado.demandado = (<HTMLInputElement>document.getElementById('demandado')).value;
  datosDemandado.identificador = (<HTMLInputElement>document.getElementById('demandado_identificador')).value;
  // Agregar los datos a la lista temporal
  this.listaTempDemandados[this.index]=datosDemandado;
  // Cerrar el modal
  this.closeModal();
  }

  eliminarDatosDemandado(){
    this.listaTempDemandados.splice(this.index, 1);
    // this.disableButtonEliminar='display: none'
    // this.modificar_parte=false
    // this.titulo_boton='Agregar'
    this.closeModal()
  }

  
  //==================================================================================================
  addItem() {
    this.limpiarCamposIndizacion();
    this.myModal = new bootstrap.Modal(document.getElementById('Modal_Indizador_primero'));
    this.myModal.show();
  }
  registrarItem(){
    let datosIndex: any = {};
    datosIndex.descripcion = (<HTMLInputElement>document.getElementById('indizacion_descripcion')).value;
    datosIndex.indice = (<HTMLInputElement>document.getElementById('indizacion_indice')).value;
    datosIndex.fojas = (<HTMLInputElement>document.getElementById('indizacion_fojas')).value;
    datosIndex.fecha = (<HTMLInputElement>document.getElementById('fecha_indice')).value;
    datosIndex.check_original = (<HTMLInputElement>document.getElementById('indizacion_checkbox_original')).checked;
    datosIndex.check_copia = (<HTMLInputElement>document.getElementById('indizacion_checkbox_copia')).checked;
    datosIndex.check_color = (<HTMLInputElement>document.getElementById('indizacion_checkbox_color')).checked;
    datosIndex.check_escalagris = (<HTMLInputElement>document.getElementById('indizacion_checkbox_escalagris')).checked;
    datosIndex.check_textarea = (<HTMLInputElement>document.getElementById('indizacion_textarea')).value;
    datosIndex.subItems=[]

    this.dataIndizacion.push(datosIndex)
    this.closeModal()
  }

  addSubItem(items: any[], index: number) {
    this.limpiarCamposIndizacion()
    this.modificar_indizacion=false
    this.itemTemp=items
    this.index_indizacion=index
    this.myModal = new bootstrap.Modal(document.getElementById('Modal_Indizador_segundo'));
    this.myModal.show();

    const botonRegistrar = document.getElementById('boton_agregar_subitem');
    if (botonRegistrar) {
      botonRegistrar.onclick = () => this.registrarSubItem(items, index);
    }
  }
  registrarSubItem(items: any[], index: number){
    let datosIndex: any = {};
    datosIndex.descripcion = (<HTMLInputElement>document.getElementById('indizacion_descripcion_2')).value;
    datosIndex.indice = (<HTMLInputElement>document.getElementById('indizacion_indice_2')).value;
    datosIndex.fojas = (<HTMLInputElement>document.getElementById('indizacion_fojas_2')).value;
    datosIndex.fecha = (<HTMLInputElement>document.getElementById('fecha_indice_2')).value;
    datosIndex.check_original = (<HTMLInputElement>document.getElementById('indizacion_checkbox_original_2')).checked;
    datosIndex.check_copia = (<HTMLInputElement>document.getElementById('indizacion_checkbox_copia_2')).checked;
    datosIndex.check_color = (<HTMLInputElement>document.getElementById('indizacion_checkbox_color_2')).checked;
    datosIndex.check_escalagris = (<HTMLInputElement>document.getElementById('indizacion_checkbox_escalagris_2')).checked;
    datosIndex.check_textarea = (<HTMLInputElement>document.getElementById('indizacion_textarea_2')).value;
    // datosIndex.subItems=[]
    if (datosIndex) {
      if (!items[index].subItems) {
        items[index].subItems = [];
      }
      items[index].subItems.push(datosIndex);
    }
    this.closeModal()
    
  }

  editItem(items: any[], index: number) {
    this.limpiarCamposIndizacion()
    this.modificar_indizacion=true
    this.itemTemp=items
    this.index_indizacion=index
    this.myModal = new bootstrap.Modal(document.getElementById('Modal_Indizador_segundo'));
    this.myModal.show();

      (<HTMLInputElement>document.getElementById('indizacion_descripcion_2')).value=items[index].descripcion;
      (<HTMLInputElement>document.getElementById('indizacion_indice_2')).value=items[index].indice;
      (<HTMLInputElement>document.getElementById('indizacion_fojas_2')).value=items[index].fojas;
      (<HTMLInputElement>document.getElementById('fecha_indice_2')).value=items[index].fecha;
      (<HTMLInputElement>document.getElementById('indizacion_checkbox_original_2')).checked=items[index].check_original;
      (<HTMLInputElement>document.getElementById('indizacion_checkbox_copia_2')).checked=items[index].check_copia;
      (<HTMLInputElement>document.getElementById('indizacion_checkbox_color_2')).checked=items[index].check_color;
      (<HTMLInputElement>document.getElementById('indizacion_checkbox_escalagris_2')).checked=items[index].check_escalagris;
      (<HTMLInputElement>document.getElementById('indizacion_textarea_2')).value=items[index].check_textarea;
            
    const botonRegistrar = document.getElementById('boton_agregar_subitem');
    if (botonRegistrar) {
      botonRegistrar.onclick = () => this.registrarModificarItem(items, index);
    }
  }

  registrarModificarItem(items: any[], index: number){
          items[index].descripcion = (<HTMLInputElement>document.getElementById('indizacion_descripcion_2')).value;
          items[index].indice = (<HTMLInputElement>document.getElementById('indizacion_indice_2')).value;
          items[index].fojas = (<HTMLInputElement>document.getElementById('indizacion_fojas_2')).value;
          items[index].fecha = (<HTMLInputElement>document.getElementById('fecha_indice_2')).value;
          items[index].check_original = (<HTMLInputElement>document.getElementById('indizacion_checkbox_original_2')).checked;
          items[index].check_copia = (<HTMLInputElement>document.getElementById('indizacion_checkbox_copia_2')).checked;
          items[index].check_color = (<HTMLInputElement>document.getElementById('indizacion_checkbox_color_2')).checked;
          items[index].check_escalagris = (<HTMLInputElement>document.getElementById('indizacion_checkbox_escalagris_2')).checked;
          items[index].check_textarea = (<HTMLInputElement>document.getElementById('indizacion_textarea_2')).value;

          this.closeModal()
  }

  deleteItem(items: any[], index: number) {
    items.splice(index, 1);
  }
}
